//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_LEGAL_CASE
    {
        public string CASE_CODE { get; set; }
        public string CASE_NAME_TH { get; set; }
        public string CASE_NAME_EN { get; set; }
        public string CASE_GROUP_CODE { get; set; }
        public string CASE_TYPE { get; set; }
        public string CASE_COLOR { get; set; }
        public string CASE_DOC_FLAG { get; set; }
        public string CASE_TABLE { get; set; }
        public Nullable<int> CASE_SEQ { get; set; }
        public string CASE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> CASE_CREATE_DATE { get; set; }
        public string CASE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CASE_UPDATE_DATE { get; set; }
        public string CASE_STATUS { get; set; }
    }
}
