//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_OA_GROUP
    {
        public string OAGROUP_CODE { get; set; }
        public string OAGROUP_NAME_TH { get; set; }
        public string OAGROUP_NAME_EN { get; set; }
        public Nullable<int> OAGROUP_EXPIRED_DAY { get; set; }
        public string OAGROUP_CREATE_BY { get; set; }
        public Nullable<System.DateTime> OAGROUP_CREATE_DATE { get; set; }
        public string OAGROUP_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> OAGROUP_UPDATE_DATE { get; set; }
        public string OAGROUP_STATUS { get; set; }
    }
}
