//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PROGRAM
    {
        public string PROG_CODE { get; set; }
        public string PROG_NAME { get; set; }
        public Nullable<int> PROG_LEVEL { get; set; }
        public string PROG_PARENT_CODE { get; set; }
        public string PROG_TARGET_URL { get; set; }
        public Nullable<int> PROG_ORDER { get; set; }
        public string PROG_ICON { get; set; }
        public string PROG_CREATE_BY { get; set; }
        public Nullable<System.DateTime> PROG_CREATE_DATE { get; set; }
        public string PROG_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> PROG_UPDATE_DATE { get; set; }
        public string PROG_STATUS { get; set; }
    }
}
