//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ROLE
    {
        public string ROLE_CODE { get; set; }
        public string ROLE_NAME { get; set; }
        public int ROLE_DATA_LEVEL { get; set; }
        public string ROLE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> ROLE_CREATE_DATE { get; set; }
        public string ROLE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> ROLE_UPDATE_DATE { get; set; }
        public string ROLE_STATUS { get; set; }
    }
}
