//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SIGNATURE
    {
        public int WO_ID { get; set; }
        public string WO_C_PROPOSE_1 { get; set; }
        public string WO_C_PROPOSE_2 { get; set; }
        public string WO_C_APPROVED_1 { get; set; }
        public string WO_C_APPROVED_2 { get; set; }
        public string WO_C_APPROVED_3 { get; set; }
        public string WO_C_APPROVED_4 { get; set; }
        public string WO_C_POSITION_1 { get; set; }
        public string WO_C_POSITION_2 { get; set; }
        public string WO_C_POSITION_3 { get; set; }
        public string WO_C_POSITION_4 { get; set; }
        public string WO_C_POSITION_5 { get; set; }
        public string WO_C_POSITION_6 { get; set; }
        public string WO_S_REVIEWED_1 { get; set; }
        public string WO_S_REVIEWED_2 { get; set; }
        public string WO_S_REVIEWED_3 { get; set; }
        public string WO_S_APPROVED_1 { get; set; }
        public string WO_S_APPROVED_2 { get; set; }
        public string WO_S_APPROVED_3 { get; set; }
        public string WO_S_POSITION_1 { get; set; }
        public string WO_S_POSITION_2 { get; set; }
        public string WO_S_POSITION_3 { get; set; }
        public string WO_S_POSITION_4 { get; set; }
        public string WO_S_POSITION_5 { get; set; }
        public string WO_S_POSITION_6 { get; set; }
    }
}
