//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_STATUS
    {
        public string STS_CODE { get; set; }
        public string STS_NAME_TH { get; set; }
        public string STS_NAME_EN { get; set; }
        public string STS_CREATE_BY { get; set; }
        public Nullable<System.DateTime> STS_CREATE_DATE { get; set; }
        public string STS_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> STS_UPDATE_DATE { get; set; }
        public string STS_STATUS { get; set; }
    }
}
