//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TAX_CONFIG
    {
        public int TAX_NO { get; set; }
        public string TAX_TYPE { get; set; }
        public Nullable<decimal> TAX_START { get; set; }
        public Nullable<decimal> TAX_END { get; set; }
        public Nullable<decimal> TAX_RATE { get; set; }
        public Nullable<int> TAX_SEQ { get; set; }
        public Nullable<System.DateTime> EFF_FROM_DATE { get; set; }
        public Nullable<System.DateTime> EFF_TO_DATE { get; set; }
    }
}
