//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_WRITEOFF_SUBTYPE
    {
        public string SUBTYPE_CODE { get; set; }
        public string SUBTYPE_NAME_TH { get; set; }
        public string SUBTYPE_NAME_EN { get; set; }
        public string SUBTYPE_GROUPE_CODE { get; set; }
        public string SUBTYPE_OS_FLAG { get; set; }
        public Nullable<decimal> SUBTYPE_OS_MIN { get; set; }
        public Nullable<decimal> SUBTYPE_OS_MAX { get; set; }
        public string SUBTYPE_R3_FLAG { get; set; }
        public Nullable<int> SUBTYPE_R3_DAY { get; set; }
        public string SUBTYPE_REPO_FLAG { get; set; }
        public string SUBTYPE_REPO_STATUS { get; set; }
        public string SUBTYPE_AUCTION_FLAG { get; set; }
        public string SUBTYPE_OVD_FLAG { get; set; }
        public Nullable<int> SUBTYPE_OVD_DAY { get; set; }
        public string SUBTYPE_REDCODE { get; set; }
        public string SUBTYPE_BLACKCODE { get; set; }
        public string SUBTYPE_WO_CAIMTAX { get; set; }
        public string SUBTYPE_WO_CAIMTAX_STATUS { get; set; }
        public string SUBTYPE_WO_COMP { get; set; }
        public string SUBTYPE_WO_COMP_STATUS { get; set; }
        public string SUBTYPE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SUBTYPE_CREATE_DATE { get; set; }
        public string SUBTYPE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> SUBTYPE_UPDATE_DATE { get; set; }
        public string SUBTYPE_STATUS { get; set; }
    }
}
