//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_PMT_SCHEDULE
    {
        public string CONTRACT_NO { get; set; }
        public int PAYMENT_ID { get; set; }
        public string PAYMENT_APPLICATION_STATUS { get; set; }
        public string DELINQUENCY_STATUS { get; set; }
        public Nullable<decimal> INTEREST_RATE { get; set; }
        public Nullable<System.DateTime> CALCULATED_PAYMENT_DATE { get; set; }
        public Nullable<System.DateTime> SCHEDULED_PAYMENT_DATE { get; set; }
        public Nullable<decimal> SCHEDULED_PRINCIPAL_AMNT { get; set; }
        public Nullable<decimal> SCHEDULED_INTEREST_AMNT { get; set; }
        public Nullable<decimal> SCHEDULED_SERVICES_AMNT { get; set; }
        public Nullable<decimal> SCHEDULED_TAX_AMNT { get; set; }
        public Nullable<decimal> SCHEDULED_FEE_AMNT { get; set; }
        public Nullable<decimal> UNPAID_PRINCIPAL_BALANCE_AMNT { get; set; }
        public Nullable<decimal> OUTSTANDING_PRINCIPAL_AMNT { get; set; }
        public Nullable<decimal> ACCRUED_OUTSTANDING_INTEREST_AMNT { get; set; }
        public Nullable<decimal> OUTSTANDING_SERVICES_AMNT { get; set; }
        public Nullable<decimal> OUTSTANDING_TAX_AMNT { get; set; }
        public Nullable<decimal> OUTSTANDING_FEE_AMNT { get; set; }
        public Nullable<System.DateTime> ACTUAL_PAYMENT_DATE { get; set; }
        public Nullable<decimal> TOTAL_CUST_PAYMENT_AMNT { get; set; }
        public string RECORD_STATUS { get; set; }
        public Nullable<decimal> BONUS_AMNT { get; set; }
        public Nullable<System.DateTime> DATA_IMPORT_DATE { get; set; }
    }
}
