//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_OVERDUE
    {
        public string CONTRACT_NO { get; set; }
        public Nullable<System.DateTime> OVERDUE_SINCE { get; set; }
        public Nullable<System.DateTime> DELINQUENT_SINCE { get; set; }
        public Nullable<int> OVERDUE_DAYS { get; set; }
        public Nullable<int> DELINQUENCY_DAYS { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
