//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_INTERACTION
    {
        public string CONTRACT_NO { get; set; }
        public int INTERACTION_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string INTERACTION_NOTES { get; set; }
        public string INTERACTION_TYPE { get; set; }
        public string INTERACTION_SUB_TYPE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> DATA_IMPORT_DATE { get; set; }
    }
}
