//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EXPENSE_H
    {
        public string EXPENSE_ID { get; set; }
        public Nullable<System.DateTime> EXPENSE_DATE { get; set; }
        public string EXPENSE_INVOICE_NO { get; set; }
        public string EXPENSE_REMARK { get; set; }
        public string EXPENSE_BENEFICIARY_TYPE { get; set; }
        public string EXPENSE_BENEFICIARY { get; set; }
        public string EXPENSE_APPROVE_FLAG { get; set; }
        public string EXPENSE_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> EXPENSE_APPROVE_DATE { get; set; }
        public string EXPENSE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> EXPENSE_CREATE_DATE { get; set; }
        public string EXPENSE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> EXPENSE_UPDATE_DATE { get; set; }
        public string EXPENSE_STATUS { get; set; }
        public string EXPENSE_TYPE { get; set; }
    }
}
