//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JOB_REPO
    {
        public string JOB_ID { get; set; }
        public string JOB_CONTRACT_NO { get; set; }
        public string JOB_CASE { get; set; }
        public string JOB_LEGAL_STATUS { get; set; }
        public string JOB_REPO_STATUS { get; set; }
        public Nullable<int> JOB_BASE_COUNT { get; set; }
        public string JOB_REALLOCATE_FLAG { get; set; }
        public string JOB_CUST_CODE { get; set; }
        public string JOB_CUST_NAME { get; set; }
        public string JOB_CUST_TYPE { get; set; }
        public string JOB_CARD_NO { get; set; }
        public string JOB_ADMIN_CODE { get; set; }
        public string JOB_OA_CODE { get; set; }
        public Nullable<System.DateTime> JOB_DUE_DATE { get; set; }
        public Nullable<int> JOB_DUE_DAY { get; set; }
        public Nullable<decimal> JOB_INST_AMT { get; set; }
        public string JOB_BUCKET { get; set; }
        public Nullable<decimal> JOB_INST_PAID { get; set; }
        public Nullable<decimal> JOB_PAID_TERM { get; set; }
        public Nullable<decimal> JOB_OS_AMT { get; set; }
        public Nullable<decimal> JOB_OVD_AMT { get; set; }
        public Nullable<int> JOB_OVD_DAY { get; set; }
        public Nullable<decimal> JOB_OVD_TERM { get; set; }
        public string JOB_BRAND { get; set; }
        public string JOB_MODEL { get; set; }
        public string JOB_PLATE_NO { get; set; }
        public string JOB_ASSET_DESC { get; set; }
        public Nullable<System.DateTime> JOB_EXPIRE_DATE { get; set; }
        public string JOB_DOC_FLAG { get; set; }
        public Nullable<System.DateTime> JOB_ASSIGN_ADMIN_DATE { get; set; }
        public Nullable<System.DateTime> JOB_ASSIGN_OA_DATE { get; set; }
        public string JOB_ASSIGN_REMARK { get; set; }
        public Nullable<System.DateTime> JOB_R3_SEND_DATE { get; set; }
        public Nullable<System.DateTime> JOB_R3_RECEVIE_DATE { get; set; }
        public string JOB_OA_SUCCESS { get; set; }
        public string JOB_CAR_PARK { get; set; }
        public Nullable<System.DateTime> JOB_REPO_DATE { get; set; }
        public Nullable<System.DateTime> JOB_TRANS_DATE { get; set; }
        public Nullable<decimal> JOB_MILEAGE { get; set; }
        public string JOB_REPO_TYPE { get; set; }
        public Nullable<System.DateTime> JOB_CHARGE_DATE { get; set; }
        public Nullable<decimal> JOB_FEE_EXPENSE { get; set; }
        public Nullable<decimal> JOB_REPO_EXPENSE { get; set; }
        public Nullable<decimal> JOB_OTHER_EXPENSE { get; set; }
        public string JOB_RECEIVE_REMARK { get; set; }
        public string JOB_NOTI_FLAG { get; set; }
        public Nullable<System.DateTime> JOB_RPS_DATE { get; set; }
        public string JOB_PROVINCE_CODE { get; set; }
        public string JOB_PROVINCE_REPO { get; set; }
        public string JOB_GEN_FLAG { get; set; }
        public string JOB_R3_ID { get; set; }
        public Nullable<System.DateTime> JOB_STEP_DATE { get; set; }
        public string JOB_CREATE_BY { get; set; }
        public Nullable<System.DateTime> JOB_CREATE_DATE { get; set; }
        public string JOB_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> JOB_UPDATE_DATE { get; set; }
        public string JOB_STATUS { get; set; }
    }
}
