//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LEGAL_ATTACHMENT
    {
        public string ATTACH_JOB_ID { get; set; }
        public int ATTACH_SEQUENCE { get; set; }
        public string ATTACH_FILE_NAME { get; set; }
        public string ATTACH_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> ATTACH_DATE { get; set; }
        public string ATTACH_BY { get; set; }
    }
}
