//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LEGAL_TRACKING
    {
        public string LEGAL_JOB_ID { get; set; }
        public int LEGAL_SEQ_NO { get; set; }
        public string LEGAL_CASE { get; set; }
        public string LEGAL_CONTRACT_NO { get; set; }
        public Nullable<System.DateTime> LEGAL_TRACKING_DATE { get; set; }
        public string LEGAL_TRACKING_BY { get; set; }
        public Nullable<System.DateTime> LEGAL_MAILING_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_FILING_DATE { get; set; }
        public string LEGAL_STATUS { get; set; }
        public string LEGAL_DEBTOR_STATUS { get; set; }
        public string LEGAL_BLACK_CODE { get; set; }
        public string LEGAL_RED_CODE { get; set; }
        public string LEGAL_ATTORNEY_STATUS { get; set; }
        public string LEGAL_COURT_CODE { get; set; }
        public Nullable<decimal> LEGAL_COURT_FEE { get; set; }
        public Nullable<decimal> LEGAL_AMOUNT_CLAIMED { get; set; }
        public string LEGAL_POLICE_STATION { get; set; }
        public string LEGAL_CAR_RECEIVED_PLACE { get; set; }
        public Nullable<System.DateTime> LEGAL_SUBMISSION_DATE { get; set; }
        public Nullable<decimal> LEGAL_SUBMISSION_AMOUNT { get; set; }
        public Nullable<System.DateTime> LEGAL_CONTRACT_TERMINATED_DATE { get; set; }
        public Nullable<decimal> LEGAL_LACK_OF_BENEFIT { get; set; }
        public string LEGAL_CHEQUE_NO { get; set; }
        public Nullable<System.DateTime> LEGAL_NOTIFY_CHEQUE_DATE { get; set; }
        public string LEGAL_PARTY_IN_LAW_SUIT { get; set; }
        public Nullable<System.DateTime> LEGAL_APPOINTED_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_ASSIGNED_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_ATTORNEY_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_NOTICE_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_WITNESS_DATE { get; set; }
        public string LEGAL_WITNESS_TIME { get; set; }
        public Nullable<decimal> LEGAL_LAWYER_FEE { get; set; }
        public Nullable<decimal> LEGAL_SECOND_LAWYER_FEE { get; set; }
        public Nullable<System.DateTime> LEGAL_ENFORCEMENT_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_BANKRUPTCY_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_BANKRUPTCY_DISCHARGED_DATE { get; set; }
        public string LEGAL_POL_NO { get; set; }
        public string LEGAL_STOLEN_NO { get; set; }
        public Nullable<System.DateTime> LEGAL_APPOINTMENT_CHECK_DATE { get; set; }
        public string LEGAL_OA_ENFORCEMENT { get; set; }
        public Nullable<System.DateTime> LEGAL_SUBMIT_ENFORCEMENT_DATE { get; set; }
        public string LEGAL_OA_ASSET_SEARCH { get; set; }
        public Nullable<System.DateTime> LEGAL_SUBMIT_INVEST_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_ENFORCEMENT_EFF_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_CASH_RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_SEIZE_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_REPORT_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_JUDGMENT_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_WITHDRAW_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_EXECUTION_DATE { get; set; }
        public Nullable<System.DateTime> LEGAL_EXECUTION_END_DATE { get; set; }
        public string LEGAL_DETAILS { get; set; }
        public Nullable<System.DateTime> LEGAL_CREATE_DATE { get; set; }
        public string LEGAL_CREATE_BY { get; set; }
        public Nullable<System.DateTime> LEGAL_UPDATE_DATE { get; set; }
        public string LEGAL_UPDATE_BY { get; set; }
    }
}
