//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WRITEOFF_H
    {
        public string WRITEOFF_DOC_ID { get; set; }
        public Nullable<System.DateTime> WRITEOFF_DATE { get; set; }
        public string WRITEOFF_TYPE { get; set; }
        public string WRITEOFF_SUBTYPE { get; set; }
        public string WRITEOFF_APPROVE_FLAG { get; set; }
        public string WRITEOFF_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> WRITEOFF_APPROVE_DATE { get; set; }
        public string WRITEOFF_CREATE_BY { get; set; }
        public Nullable<System.DateTime> WRITEOFF_CREATE_DATE { get; set; }
        public string WRITEOFF_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> WRITEOFF_UPDATE_DATE { get; set; }
        public string WRITEOFF_STATUS { get; set; }
    }
}
