//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.DOMAIN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WRITEOFF_D
    {
        public int WRITEOFFD_ID { get; set; }
        public string WRITEOFFD_HID { get; set; }
        public string WRITEOFFD_CONTRACT_NO { get; set; }
        public Nullable<decimal> WRITEOFFD_OS { get; set; }
        public string WRITEOFFD_R3_STATUS { get; set; }
        public Nullable<int> WRITEOFFD_R3_DAY { get; set; }
        public string WRITEOFFD_REPO_FLAG { get; set; }
        public string WRITEOFFD_AUCTION_FLAG { get; set; }
        public Nullable<int> WRITEOFFD_OVD_DAY { get; set; }
        public string WRITEOFFD_REDCODE { get; set; }
        public string WRITEOFFD_BLACKCODE { get; set; }
        public string WRITEOFFD_CAIMTAX_STATUS { get; set; }
        public string WRITEOFFD_COMPANY_STATUS { get; set; }
        public string WRITEOFFD_REPO_STATUS { get; set; }
        public string WRITEOFFD_LEGAL_STATUS { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_FILING_DATE { get; set; }
        public string WRITEOFFD_COURTCODE { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_SUBMIT_ENFORCEMENT_DATE { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_SUBMIT_INVEST_DATE { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_ENFORCEMENT_EFF_DATE { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_REPORT_DATE { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_JUDGMENT_DATE { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_EXECUTION_DATE { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_EXECUTION_END_DATE { get; set; }
        public string WRITEOFFD_REMARK { get; set; }
        public Nullable<decimal> WRITEOFFD_JD_TOTAL { get; set; }
        public string WRITEOFFD_CREATE_BY { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_CREATE_DATE { get; set; }
        public string WRITEOFFD_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> WRITEOFFD_UPDATE_DATE { get; set; }
        public string WRITEOFFD_STATUS { get; set; }
    }
}
