//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COL_USER
    {
        public string USER_CODE { get; set; }
        public string USER_PASSWORD { get; set; }
        public string FIRST_NAME_EN { get; set; }
        public string FIRST_NAME_TH { get; set; }
        public string LAST_NAME_EN { get; set; }
        public string LAST_NAME_TH { get; set; }
        public string USER_GROUP { get; set; }
        public string USER_STATUS { get; set; }
        public Nullable<int> LOGIN_COUNTER { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
