//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ACTION
    {
        public string ACT_CODE { get; set; }
        public string ACT_PROG_CODE { get; set; }
        public string ACT_NAME { get; set; }
        public string ACT_CREATE_BY { get; set; }
        public Nullable<System.DateTime> ACT_CREATE_DATE { get; set; }
        public string ACT_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> ACT_UPDATE_DATE { get; set; }
        public string ACT_STATUS { get; set; }
    }
}
