//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BUCKET
    {
        public string BUCKET_CODE { get; set; }
        public string BUCKET_NAME { get; set; }
        public string BUCKET_DESC { get; set; }
        public Nullable<int> BUCKET_OVDDAYS_START { get; set; }
        public Nullable<int> BUCKET_OVDDAYS_END { get; set; }
        public string BUCKET_CREATE_BY { get; set; }
        public Nullable<System.DateTime> BUCKET_CREATE_DATE { get; set; }
        public string BUCKET_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> BUCKET_UPDATE_DATE { get; set; }
        public string BUCKET_STATUS { get; set; }
        public string BUCKET_COMP_CODE { get; set; }
        public string BUCKET_BRANCH_CODE { get; set; }
    }
}
