//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_COURT
    {
        public string COURT_CODE { get; set; }
        public string COURT_NAME_TH { get; set; }
        public string COURT_NAME_EN { get; set; }
        public string COURT_TYPE { get; set; }
        public Nullable<decimal> COURT_AMT { get; set; }
        public string COURT_CREATE_BY { get; set; }
        public Nullable<System.DateTime> COURT_CREATE_DATE { get; set; }
        public string COURT_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> COURT_UPDATE_DATE { get; set; }
        public string COURT_STATUS { get; set; }
    }
}
