//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DOCUMENT
    {
        public string DOC_CASE_CODE { get; set; }
        public string DOC_CODE { get; set; }
        public string DOC_REQ_FLAG { get; set; }
        public string DOC_CREATE_BY { get; set; }
        public Nullable<System.DateTime> DOC_CREATE_DATE { get; set; }
        public string DOC_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DOC_UPDATE_DATE { get; set; }
        public string DOC_STATUS { get; set; }
    }
}
