//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FUNCTION
    {
        public string FUNC_CODE { get; set; }
        public string FUNC_PROG_CODE { get; set; }
        public string FUNC_NAME { get; set; }
        public string FUNC_CREATE_BY { get; set; }
        public Nullable<System.DateTime> FUNC_CREATE_DATE { get; set; }
        public string FUNC_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> FUNC_UPDATE_DATE { get; set; }
        public string FUNC_STATUS { get; set; }
    }
}
