//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MASTER
    {
        public string MASTER_CODE { get; set; }
        public string MASTER_TYPE { get; set; }
        public string MASTER_NAME_TH { get; set; }
        public string MASTER_NAME_EN { get; set; }
        public string MASTER_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MASTER_CREATE_DATE { get; set; }
        public string MASTER_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MASTER_UPDATE_DATE { get; set; }
        public string MASTER_STATUS { get; set; }
    }
}
