//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_OA_CONFIG_BUCKET
    {
        public string MOB_OA_CODE { get; set; }
        public string MOB_BUCKET_CODE { get; set; }
        public Nullable<int> MOB_LIMIT_PERCENTAGE { get; set; }
        public Nullable<int> MOB_LIMIT_JOBS { get; set; }
        public string MOB_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MOB_CREATE_DATE { get; set; }
        public string MOB_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MOB_UPDATE_DATE { get; set; }
        public string MOB_STATUS { get; set; }
    }
}
