//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_OA_CONFIG_AREA
    {
        public string MOA_OA_CODE { get; set; }
        public string MOA_BUCKET_CODE { get; set; }
        public string MOA_PROVINCE_CODE { get; set; }
    }
}
