//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_OA
    {
        public string OA_CODE { get; set; }
        public string OA_NAME_TH { get; set; }
        public string OA_NAME_EN { get; set; }
        public string OA_GROUP_CODE { get; set; }
        public string OA_REPO_FLAG { get; set; }
        public string OA_LEGAL_FLAG { get; set; }
        public string OA_TYPE { get; set; }
        public string OA_CREATE_BY { get; set; }
        public Nullable<System.DateTime> OA_CREATE_DATE { get; set; }
        public string OA_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> OA_UPDATE_DATE { get; set; }
        public string OA_STATUS { get; set; }
    }
}
