//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PARAMETER
    {
        public string PARA_CODE { get; set; }
        public string PARA_NAME { get; set; }
        public string PARA_DESC { get; set; }
        public string PARA_DATA_TYPE { get; set; }
        public string PARA_VALUE { get; set; }
        public string PARA_DEFAULT_VALUE { get; set; }
        public string PARA_CREATE_BY { get; set; }
        public Nullable<System.DateTime> PARA_CREATE_DATE { get; set; }
        public string PARA_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> PARA_UPDATE_DATE { get; set; }
        public string PARA_STATUS { get; set; }
    }
}
