//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PROVINCE
    {
        public string PROVINCE_CODE { get; set; }
        public string PROVINCE_NAME { get; set; }
        public string PROVINCE_GEOGRAPHYCODE { get; set; }
        public Nullable<int> PROVINCE_KM { get; set; }
        public string PROVINCE_CREATEBY { get; set; }
        public Nullable<System.DateTime> PROVINCE_CREATEDATE { get; set; }
        public string PROVINCE_UPDATEBY { get; set; }
        public Nullable<System.DateTime> PROVINCE_UPDATEDATE { get; set; }
        public string PROVINCE_STATUS { get; set; }
    }
}
