//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TRANS_DETAIL
    {
        public int TRANSD_ID { get; set; }
        public string TRANSD_TRANS_CODE { get; set; }
        public string TRANSD_EXPENSE_FLAG { get; set; }
        public Nullable<decimal> TRANSD_FROM { get; set; }
        public Nullable<decimal> TRANSD_TO { get; set; }
        public Nullable<decimal> TRANSD_VALUE { get; set; }
        public string TRANSD_FIELD { get; set; }
    }
}
