//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_USER
    {
        public string USER_LOGIN { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_FIRST_NAME { get; set; }
        public string USER_LAST_NAME { get; set; }
        public string USER_AD_FLAG { get; set; }
        public string USER_CREATE_BY { get; set; }
        public Nullable<System.DateTime> USER_CREATE_DATE { get; set; }
        public string USER_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> USER_UPDATE_DATE { get; set; }
        public string USER_STATUS { get; set; }
    }
}
