//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_USER_ROLE
    {
        public string USERROLE_USER_LOGIN { get; set; }
        public string USERROLE_ROLE_CODE { get; set; }
        public string USERROLE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> USERROLE_CREATE_DATE { get; set; }
        public string USERROLE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> USERROLE_UPDATE_DATE { get; set; }
        public string USERROLE_STATUS { get; set; }
    }
}
