//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_JDC_H
    {
        public string JD_ID { get; set; }
        public string JD_CASE_CODE { get; set; }
        public string JD_CASE { get; set; }
        public string JD_CONTRACT_NO { get; set; }
        public string JD_COMPROMIST_TYPE { get; set; }
        public string JD_TYPE { get; set; }
        public string JD_JOB_ID { get; set; }
        public string JD_CONTRACT_LIST { get; set; }
        public string JD_CHEQUE_LIST { get; set; }
        public string JD_DEBTOR_STATUS_CODE { get; set; }
        public string JD_DEBTOR_STATUS { get; set; }
        public Nullable<System.DateTime> JD_JUDGMENT_DATE { get; set; }
        public Nullable<System.DateTime> JD_COMPROMISE_DATE { get; set; }
        public string JD_FURTHER_COMMENT { get; set; }
        public Nullable<int> JD_TERM { get; set; }
        public Nullable<decimal> JD_TOTAL { get; set; }
        public Nullable<System.DateTime> JD_FIRST_DUE_DATE { get; set; }
        public Nullable<int> JD_PAY_DAY { get; set; }
        public string JD_APPROVE_FLAG_CODE { get; set; }
        public string JD_APPROVE_FLAG { get; set; }
        public string JD_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> JD_APPROVE_DATE { get; set; }
        public string JD_APPROVE_REMARK { get; set; }
        public string JD_REMARK { get; set; }
        public string JD_CREATE_BY { get; set; }
        public Nullable<System.DateTime> JD_CREATE_DATE { get; set; }
        public string JD_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> JD_UPDATE_DATE { get; set; }
        public string JD_STATUS { get; set; }
    }
}
