//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_LEGAL_DETAIL
    {
        public string CHQ_JOB_ID { get; set; }
        public string CHQ_CHEQUE_NO { get; set; }
        public string CHQ_CONTRACT_NO { get; set; }
        public Nullable<int> CHQ_SR_NO { get; set; }
        public string CHQ_ACCOUNT_NO { get; set; }
        public string CHQ_BANK_ID { get; set; }
        public string CHQ_BANK_NAME { get; set; }
        public string CHQ_BRANCH_NAME { get; set; }
        public string CHQ_BORROWER_NAME { get; set; }
        public string CHQ_CHEQUE_CLEARING_CODE { get; set; }
        public Nullable<System.DateTime> CHQ_DEPOSIT_DATE { get; set; }
        public Nullable<System.DateTime> CHQ_UPLOAD_DATE { get; set; }
        public Nullable<System.DateTime> CHQ_DUE_DATE { get; set; }
        public Nullable<decimal> CHQ_EMI_AMOUNT { get; set; }
    }
}
