//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NCLSEntities : DbContext
    {
        public NCLSEntities()
            : base("name=NCLSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COL_USER> COL_USER { get; set; }
        public virtual DbSet<COL_USER_CONTRACT> COL_USER_CONTRACT { get; set; }
        public virtual DbSet<M_ACTION> M_ACTION { get; set; }
        public virtual DbSet<M_BUCKET> M_BUCKET { get; set; }
        public virtual DbSet<M_COURT> M_COURT { get; set; }
        public virtual DbSet<M_DOCUMENT> M_DOCUMENT { get; set; }
        public virtual DbSet<M_FUNCTION> M_FUNCTION { get; set; }
        public virtual DbSet<M_LEGAL_CASE> M_LEGAL_CASE { get; set; }
        public virtual DbSet<M_LEGAL_STATUS> M_LEGAL_STATUS { get; set; }
        public virtual DbSet<M_MASTER> M_MASTER { get; set; }
        public virtual DbSet<M_OA> M_OA { get; set; }
        public virtual DbSet<M_OA_CONFIG_AREA> M_OA_CONFIG_AREA { get; set; }
        public virtual DbSet<M_OA_CONFIG_BUCKET> M_OA_CONFIG_BUCKET { get; set; }
        public virtual DbSet<M_OA_GROUP> M_OA_GROUP { get; set; }
        public virtual DbSet<M_PARAMETER> M_PARAMETER { get; set; }
        public virtual DbSet<M_PERMISSION> M_PERMISSION { get; set; }
        public virtual DbSet<M_PROGRAM> M_PROGRAM { get; set; }
        public virtual DbSet<M_PROVINCE> M_PROVINCE { get; set; }
        public virtual DbSet<M_REPO_FEE> M_REPO_FEE { get; set; }
        public virtual DbSet<M_ROLE> M_ROLE { get; set; }
        public virtual DbSet<M_SIGNATURE> M_SIGNATURE { get; set; }
        public virtual DbSet<M_STATUS> M_STATUS { get; set; }
        public virtual DbSet<M_TAX_CONFIG> M_TAX_CONFIG { get; set; }
        public virtual DbSet<M_TRANS_DETAIL> M_TRANS_DETAIL { get; set; }
        public virtual DbSet<M_TRANSACTION> M_TRANSACTION { get; set; }
        public virtual DbSet<M_USER> M_USER { get; set; }
        public virtual DbSet<M_USER_ROLE> M_USER_ROLE { get; set; }
        public virtual DbSet<M_WRITEOFF_SUBTYPE> M_WRITEOFF_SUBTYPE { get; set; }
        public virtual DbSet<S_CONTRACT_CHEQUE> S_CONTRACT_CHEQUE { get; set; }
        public virtual DbSet<S_CONTRACT_COST> S_CONTRACT_COST { get; set; }
        public virtual DbSet<S_CONTRACT_CUST> S_CONTRACT_CUST { get; set; }
        public virtual DbSet<S_CONTRACT_CUST_ADDRESS> S_CONTRACT_CUST_ADDRESS { get; set; }
        public virtual DbSet<S_CONTRACT_DELINQUENCY> S_CONTRACT_DELINQUENCY { get; set; }
        public virtual DbSet<S_CONTRACT_INTERACTION> S_CONTRACT_INTERACTION { get; set; }
        public virtual DbSet<S_CONTRACT_OVERDUE> S_CONTRACT_OVERDUE { get; set; }
        public virtual DbSet<S_CONTRACT_PMT_RECEIPT> S_CONTRACT_PMT_RECEIPT { get; set; }
        public virtual DbSet<S_CONTRACT_PMT_SCHEDULE> S_CONTRACT_PMT_SCHEDULE { get; set; }
        public virtual DbSet<S_CUSTOMER_DETAIL> S_CUSTOMER_DETAIL { get; set; }
        public virtual DbSet<S_RPS> S_RPS { get; set; }
        public virtual DbSet<T_ACT_LOG> T_ACT_LOG { get; set; }
        public virtual DbSet<T_BANKRUPTCY_FRAUD_D> T_BANKRUPTCY_FRAUD_D { get; set; }
        public virtual DbSet<T_BANKRUPTCY_FRAUD_H> T_BANKRUPTCY_FRAUD_H { get; set; }
        public virtual DbSet<T_BATCH_LOG> T_BATCH_LOG { get; set; }
        public virtual DbSet<T_CHEQUE_DETAIL> T_CHEQUE_DETAIL { get; set; }
        public virtual DbSet<T_CURRENT_LOGIN> T_CURRENT_LOGIN { get; set; }
        public virtual DbSet<T_DOCUMENT> T_DOCUMENT { get; set; }
        public virtual DbSet<T_EXPENSE_D> T_EXPENSE_D { get; set; }
        public virtual DbSet<T_EXPENSE_H> T_EXPENSE_H { get; set; }
        public virtual DbSet<T_JOB_LEGAL> T_JOB_LEGAL { get; set; }
        public virtual DbSet<T_JOB_R3> T_JOB_R3 { get; set; }
        public virtual DbSet<T_JOB_REPO> T_JOB_REPO { get; set; }
        public virtual DbSet<T_JUDGMENTDEBTOR_ATTACHMENT> T_JUDGMENTDEBTOR_ATTACHMENT { get; set; }
        public virtual DbSet<T_JUDGMENTDEBTOR_D> T_JUDGMENTDEBTOR_D { get; set; }
        public virtual DbSet<T_JUDGMENTDEBTOR_H> T_JUDGMENTDEBTOR_H { get; set; }
        public virtual DbSet<T_JUDGMENTDEBTOR_PAYMENT> T_JUDGMENTDEBTOR_PAYMENT { get; set; }
        public virtual DbSet<T_LEGAL_ATTACHMENT> T_LEGAL_ATTACHMENT { get; set; }
        public virtual DbSet<T_LEGAL_TRACKING> T_LEGAL_TRACKING { get; set; }
        public virtual DbSet<T_LOGIN_HISTORY> T_LOGIN_HISTORY { get; set; }
        public virtual DbSet<T_R3_DETAIL> T_R3_DETAIL { get; set; }
        public virtual DbSet<T_REPO_NOTE> T_REPO_NOTE { get; set; }
        public virtual DbSet<T_WRITEOFF_D> T_WRITEOFF_D { get; set; }
        public virtual DbSet<T_WRITEOFF_H> T_WRITEOFF_H { get; set; }
        public virtual DbSet<MG_JD_D> MG_JD_D { get; set; }
        public virtual DbSet<MG_JD_H> MG_JD_H { get; set; }
        public virtual DbSet<MG_JDC_D> MG_JDC_D { get; set; }
        public virtual DbSet<MG_JDC_H> MG_JDC_H { get; set; }
        public virtual DbSet<MG_LEGAL_DETAIL> MG_LEGAL_DETAIL { get; set; }
        public virtual DbSet<S_CONTRACT> S_CONTRACT { get; set; }
        public virtual DbSet<T_JOB_ALL> T_JOB_ALL { get; set; }
    
        [DbFunction("NCLSEntities", "f_split")]
        public virtual IQueryable<f_split_Result> f_split(string param, string delimiter)
        {
            var paramParameter = param != null ?
                new ObjectParameter("param", param) :
                new ObjectParameter("param", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_split_Result>("[NCLSEntities].[f_split](@param, @delimiter)", paramParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<SP_BATCH_ASSIGN_IN_HOUSE_GET_LEGAL_LC015_Result> SP_BATCH_ASSIGN_IN_HOUSE_GET_LEGAL_LC015(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BATCH_ASSIGN_IN_HOUSE_GET_LEGAL_LC015_Result>("SP_BATCH_ASSIGN_IN_HOUSE_GET_LEGAL_LC015", rowCount, errorCode, execTime);
        }
    
        public virtual ObjectResult<SP_BATCH_ASSIGN_IN_HOUSE_GET_LEGAL_LC016_Result> SP_BATCH_ASSIGN_IN_HOUSE_GET_LEGAL_LC016(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BATCH_ASSIGN_IN_HOUSE_GET_LEGAL_LC016_Result>("SP_BATCH_ASSIGN_IN_HOUSE_GET_LEGAL_LC016", rowCount, errorCode, execTime);
        }
    
        public virtual ObjectResult<SP_BATCH_ASSIGN_IN_HOUSE_GET_REPO_Result> SP_BATCH_ASSIGN_IN_HOUSE_GET_REPO(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BATCH_ASSIGN_IN_HOUSE_GET_REPO_Result>("SP_BATCH_ASSIGN_IN_HOUSE_GET_REPO", rowCount, errorCode, execTime);
        }
    
        public virtual int SP_BATCH_ASSIGN_IN_HOUSE_UPDATE_R3(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BATCH_ASSIGN_IN_HOUSE_UPDATE_R3", rowCount, errorCode, execTime);
        }
    
        public virtual ObjectResult<SP_BATCH_ASSIGN_OA_GET_CONFIG_Result> SP_BATCH_ASSIGN_OA_GET_CONFIG(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BATCH_ASSIGN_OA_GET_CONFIG_Result>("SP_BATCH_ASSIGN_OA_GET_CONFIG", rowCount, errorCode, execTime);
        }
    
        public virtual ObjectResult<SP_BATCH_ASSIGN_OA_GET_JOB_NO_OWNER_Result> SP_BATCH_ASSIGN_OA_GET_JOB_NO_OWNER(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BATCH_ASSIGN_OA_GET_JOB_NO_OWNER_Result>("SP_BATCH_ASSIGN_OA_GET_JOB_NO_OWNER", rowCount, errorCode, execTime);
        }
    
        public virtual int SP_BATCH_ASSIGN_OA_UPDATE_EXP(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BATCH_ASSIGN_OA_UPDATE_EXP", rowCount, errorCode, execTime);
        }
    
        public virtual int SP_BATCH_CONTRACT_DETAIL(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BATCH_CONTRACT_DETAIL", rowCount, errorCode, execTime);
        }
    
        public virtual ObjectResult<SP_BATCH_R3_GET_DETAIL_Result> SP_BATCH_R3_GET_DETAIL(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BATCH_R3_GET_DETAIL_Result>("SP_BATCH_R3_GET_DETAIL", rowCount, errorCode, execTime);
        }
    
        public virtual ObjectResult<SP_BATCH_R3_GET_HEADER_Result> SP_BATCH_R3_GET_HEADER(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BATCH_R3_GET_HEADER_Result>("SP_BATCH_R3_GET_HEADER", rowCount, errorCode, execTime);
        }
    
        public virtual int SP_BATCH_UPDATE_STATUS_EXP(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BATCH_UPDATE_STATUS_EXP", rowCount, errorCode, execTime);
        }
    
        public virtual int SP_BATCH_UPDATE_STATUS_R3(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BATCH_UPDATE_STATUS_R3", rowCount, errorCode, execTime);
        }
    
        public virtual int SP_BATCH_UPDATE_STATUS_REPO(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BATCH_UPDATE_STATUS_REPO", rowCount, errorCode, execTime);
        }
    
        public virtual int SP_CHECK_HOLIDAY(ObjectParameter rowCount, ObjectParameter errorCode, ObjectParameter execTime)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECK_HOLIDAY", rowCount, errorCode, execTime);
        }
    
        public virtual ObjectResult<SP_DASHBOARD_DOC_Result> SP_DASHBOARD_DOC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DASHBOARD_DOC_Result>("SP_DASHBOARD_DOC");
        }
    
        public virtual ObjectResult<SP_DASHBOARD_LEGAL_Result> SP_DASHBOARD_LEGAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DASHBOARD_LEGAL_Result>("SP_DASHBOARD_LEGAL");
        }
    
        public virtual ObjectResult<SP_DASHBOARD_LEGALCASE_Result> SP_DASHBOARD_LEGALCASE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DASHBOARD_LEGALCASE_Result>("SP_DASHBOARD_LEGALCASE");
        }
    
        public virtual ObjectResult<SP_DASHBOARD_LEGALSTATUS_Result> SP_DASHBOARD_LEGALSTATUS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DASHBOARD_LEGALSTATUS_Result>("SP_DASHBOARD_LEGALSTATUS");
        }
    
        public virtual ObjectResult<SP_DASHBOARD_R3_Result> SP_DASHBOARD_R3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DASHBOARD_R3_Result>("SP_DASHBOARD_R3");
        }
    
        public virtual ObjectResult<SP_DASHBOARD_REPO_Result> SP_DASHBOARD_REPO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DASHBOARD_REPO_Result>("SP_DASHBOARD_REPO");
        }
    
        public virtual ObjectResult<SP_EXPENSE_RECEIVE_Result> SP_EXPENSE_RECEIVE(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EXPENSE_RECEIVE_Result>("SP_EXPENSE_RECEIVE", sEARCHParameter);
        }
    
        public virtual ObjectResult<string> SP_GEN_BANKRUPTCY_FRAUD__ID(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GEN_BANKRUPTCY_FRAUD__ID", keyParameter);
        }
    
        public virtual ObjectResult<string> SP_GEN_EXPENSE_ID(string key, string oA_Code)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var oA_CodeParameter = oA_Code != null ?
                new ObjectParameter("OA_Code", oA_Code) :
                new ObjectParameter("OA_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GEN_EXPENSE_ID", keyParameter, oA_CodeParameter);
        }
    
        public virtual ObjectResult<string> SP_GEN_JUDGMENT_ID(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GEN_JUDGMENT_ID", keyParameter);
        }
    
        public virtual ObjectResult<string> SP_GEN_REPO_ID(string key, string cONTRACT_NO)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GEN_REPO_ID", keyParameter, cONTRACT_NOParameter);
        }
    
        public virtual ObjectResult<string> SP_GEN_SUGGEEST_WRITE(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GEN_SUGGEEST_WRITE", keyParameter);
        }
    
        public virtual ObjectResult<string> SP_GET_CONTRACT_NO_BY_JD_ID(string jD_ID)
        {
            var jD_IDParameter = jD_ID != null ?
                new ObjectParameter("JD_ID", jD_ID) :
                new ObjectParameter("JD_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GET_CONTRACT_NO_BY_JD_ID", jD_IDParameter);
        }
    
        public virtual ObjectResult<SP_GET_MENU_BY_ROLE_Result> SP_GET_MENU_BY_ROLE(string userRole)
        {
            var userRoleParameter = userRole != null ?
                new ObjectParameter("UserRole", userRole) :
                new ObjectParameter("UserRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_MENU_BY_ROLE_Result>("SP_GET_MENU_BY_ROLE", userRoleParameter);
        }
    
        public virtual ObjectResult<string> SP_GET_MENU_DEFAULT(string rOLE_CODE)
        {
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GET_MENU_DEFAULT", rOLE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_MAPPING_OA_AREA_Result> SP_MAPPING_OA_AREA(string oA_CODE, string bUCKET_CODE)
        {
            var oA_CODEParameter = oA_CODE != null ?
                new ObjectParameter("OA_CODE", oA_CODE) :
                new ObjectParameter("OA_CODE", typeof(string));
    
            var bUCKET_CODEParameter = bUCKET_CODE != null ?
                new ObjectParameter("BUCKET_CODE", bUCKET_CODE) :
                new ObjectParameter("BUCKET_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MAPPING_OA_AREA_Result>("SP_MAPPING_OA_AREA", oA_CODEParameter, bUCKET_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_ASSIGN_REPO_Result> SP_SEARCH_ASSIGN_REPO(string oA_CODE, string cONTRACT_NO, Nullable<decimal> oS_START, Nullable<decimal> oS_END, string dOC_STATUS, Nullable<System.DateTime> aSSIGN_DATE_FROM, Nullable<System.DateTime> aSSIGN_DATE_TO, string pROVINCE_CODE, string oA, string aDMIN_CODE, string rOLE_CODE)
        {
            var oA_CODEParameter = oA_CODE != null ?
                new ObjectParameter("OA_CODE", oA_CODE) :
                new ObjectParameter("OA_CODE", typeof(string));
    
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var oS_STARTParameter = oS_START.HasValue ?
                new ObjectParameter("OS_START", oS_START) :
                new ObjectParameter("OS_START", typeof(decimal));
    
            var oS_ENDParameter = oS_END.HasValue ?
                new ObjectParameter("OS_END", oS_END) :
                new ObjectParameter("OS_END", typeof(decimal));
    
            var dOC_STATUSParameter = dOC_STATUS != null ?
                new ObjectParameter("DOC_STATUS", dOC_STATUS) :
                new ObjectParameter("DOC_STATUS", typeof(string));
    
            var aSSIGN_DATE_FROMParameter = aSSIGN_DATE_FROM.HasValue ?
                new ObjectParameter("ASSIGN_DATE_FROM", aSSIGN_DATE_FROM) :
                new ObjectParameter("ASSIGN_DATE_FROM", typeof(System.DateTime));
    
            var aSSIGN_DATE_TOParameter = aSSIGN_DATE_TO.HasValue ?
                new ObjectParameter("ASSIGN_DATE_TO", aSSIGN_DATE_TO) :
                new ObjectParameter("ASSIGN_DATE_TO", typeof(System.DateTime));
    
            var pROVINCE_CODEParameter = pROVINCE_CODE != null ?
                new ObjectParameter("PROVINCE_CODE", pROVINCE_CODE) :
                new ObjectParameter("PROVINCE_CODE", typeof(string));
    
            var oAParameter = oA != null ?
                new ObjectParameter("OA", oA) :
                new ObjectParameter("OA", typeof(string));
    
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_ASSIGN_REPO_Result>("SP_SEARCH_ASSIGN_REPO", oA_CODEParameter, cONTRACT_NOParameter, oS_STARTParameter, oS_ENDParameter, dOC_STATUSParameter, aSSIGN_DATE_FROMParameter, aSSIGN_DATE_TOParameter, pROVINCE_CODEParameter, oAParameter, aDMIN_CODEParameter, rOLE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_ASSIGN_REPO_GEN_Result> SP_SEARCH_ASSIGN_REPO_GEN(string oA_CODE, string cONTRACT_NO, Nullable<decimal> oS_START, Nullable<decimal> oS_END, string dOC_STATUS, Nullable<System.DateTime> aSSIGN_DATE_FROM, Nullable<System.DateTime> aSSIGN_DATE_TO, string pROVINCE_CODE, string aDMIN_CODE, string rOLE_CODE)
        {
            var oA_CODEParameter = oA_CODE != null ?
                new ObjectParameter("OA_CODE", oA_CODE) :
                new ObjectParameter("OA_CODE", typeof(string));
    
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var oS_STARTParameter = oS_START.HasValue ?
                new ObjectParameter("OS_START", oS_START) :
                new ObjectParameter("OS_START", typeof(decimal));
    
            var oS_ENDParameter = oS_END.HasValue ?
                new ObjectParameter("OS_END", oS_END) :
                new ObjectParameter("OS_END", typeof(decimal));
    
            var dOC_STATUSParameter = dOC_STATUS != null ?
                new ObjectParameter("DOC_STATUS", dOC_STATUS) :
                new ObjectParameter("DOC_STATUS", typeof(string));
    
            var aSSIGN_DATE_FROMParameter = aSSIGN_DATE_FROM.HasValue ?
                new ObjectParameter("ASSIGN_DATE_FROM", aSSIGN_DATE_FROM) :
                new ObjectParameter("ASSIGN_DATE_FROM", typeof(System.DateTime));
    
            var aSSIGN_DATE_TOParameter = aSSIGN_DATE_TO.HasValue ?
                new ObjectParameter("ASSIGN_DATE_TO", aSSIGN_DATE_TO) :
                new ObjectParameter("ASSIGN_DATE_TO", typeof(System.DateTime));
    
            var pROVINCE_CODEParameter = pROVINCE_CODE != null ?
                new ObjectParameter("PROVINCE_CODE", pROVINCE_CODE) :
                new ObjectParameter("PROVINCE_CODE", typeof(string));
    
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_ASSIGN_REPO_GEN_Result>("SP_SEARCH_ASSIGN_REPO_GEN", oA_CODEParameter, cONTRACT_NOParameter, oS_STARTParameter, oS_ENDParameter, dOC_STATUSParameter, aSSIGN_DATE_FROMParameter, aSSIGN_DATE_TOParameter, pROVINCE_CODEParameter, aDMIN_CODEParameter, rOLE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_BANKRUPTCY_BY_DOC_Result> SP_SEARCH_BANKRUPTCY_BY_DOC(string dOC_NO)
        {
            var dOC_NOParameter = dOC_NO != null ?
                new ObjectParameter("DOC_NO", dOC_NO) :
                new ObjectParameter("DOC_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_BANKRUPTCY_BY_DOC_Result>("SP_SEARCH_BANKRUPTCY_BY_DOC", dOC_NOParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_BANKRUPTCY_FRAUD_Result> SP_SEARCH_BANKRUPTCY_FRAUD(string dOC_NO, string aPPROVAL_STATUS, Nullable<System.DateTime> cREATE_DATE_FROM, Nullable<System.DateTime> cREATE_DATE_TO, string tYPE, string aDMIN_CODE, string rOLE_CODE)
        {
            var dOC_NOParameter = dOC_NO != null ?
                new ObjectParameter("DOC_NO", dOC_NO) :
                new ObjectParameter("DOC_NO", typeof(string));
    
            var aPPROVAL_STATUSParameter = aPPROVAL_STATUS != null ?
                new ObjectParameter("APPROVAL_STATUS", aPPROVAL_STATUS) :
                new ObjectParameter("APPROVAL_STATUS", typeof(string));
    
            var cREATE_DATE_FROMParameter = cREATE_DATE_FROM.HasValue ?
                new ObjectParameter("CREATE_DATE_FROM", cREATE_DATE_FROM) :
                new ObjectParameter("CREATE_DATE_FROM", typeof(System.DateTime));
    
            var cREATE_DATE_TOParameter = cREATE_DATE_TO.HasValue ?
                new ObjectParameter("CREATE_DATE_TO", cREATE_DATE_TO) :
                new ObjectParameter("CREATE_DATE_TO", typeof(System.DateTime));
    
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_BANKRUPTCY_FRAUD_Result>("SP_SEARCH_BANKRUPTCY_FRAUD", dOC_NOParameter, aPPROVAL_STATUSParameter, cREATE_DATE_FROMParameter, cREATE_DATE_TOParameter, tYPEParameter, aDMIN_CODEParameter, rOLE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_CANCEL_JOB_LEGAL_Result> SP_SEARCH_CANCEL_JOB_LEGAL(string aDMIN_CODE, string rOLE_CODE)
        {
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_CANCEL_JOB_LEGAL_Result>("SP_SEARCH_CANCEL_JOB_LEGAL", aDMIN_CODEParameter, rOLE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_CANCEL_JOB_REPO_Result> SP_SEARCH_CANCEL_JOB_REPO(string aDMIN_CODE, string rOLE_CODE)
        {
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_CANCEL_JOB_REPO_Result>("SP_SEARCH_CANCEL_JOB_REPO", aDMIN_CODEParameter, rOLE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_CHEQUE_CONTRACT_Result> SP_SEARCH_CHEQUE_CONTRACT(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_CHEQUE_CONTRACT_Result>("SP_SEARCH_CHEQUE_CONTRACT", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_COURTFEES_Result> SP_SEARCH_COURTFEES(string rEF_NO, string cONTRACT_NO, string pAYMENTNOFROM, string pAYMENTNOTO, Nullable<System.DateTime> pAYMENTDATEFROM, Nullable<System.DateTime> pAYMENTDATETO, string aDMIN_CODE, string oA_CODE, string lEGALCASE, string eXPENSE_APPROVE_FLAG)
        {
            var rEF_NOParameter = rEF_NO != null ?
                new ObjectParameter("REF_NO", rEF_NO) :
                new ObjectParameter("REF_NO", typeof(string));
    
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var pAYMENTNOFROMParameter = pAYMENTNOFROM != null ?
                new ObjectParameter("PAYMENTNOFROM", pAYMENTNOFROM) :
                new ObjectParameter("PAYMENTNOFROM", typeof(string));
    
            var pAYMENTNOTOParameter = pAYMENTNOTO != null ?
                new ObjectParameter("PAYMENTNOTO", pAYMENTNOTO) :
                new ObjectParameter("PAYMENTNOTO", typeof(string));
    
            var pAYMENTDATEFROMParameter = pAYMENTDATEFROM.HasValue ?
                new ObjectParameter("PAYMENTDATEFROM", pAYMENTDATEFROM) :
                new ObjectParameter("PAYMENTDATEFROM", typeof(System.DateTime));
    
            var pAYMENTDATETOParameter = pAYMENTDATETO.HasValue ?
                new ObjectParameter("PAYMENTDATETO", pAYMENTDATETO) :
                new ObjectParameter("PAYMENTDATETO", typeof(System.DateTime));
    
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var oA_CODEParameter = oA_CODE != null ?
                new ObjectParameter("OA_CODE", oA_CODE) :
                new ObjectParameter("OA_CODE", typeof(string));
    
            var lEGALCASEParameter = lEGALCASE != null ?
                new ObjectParameter("LEGALCASE", lEGALCASE) :
                new ObjectParameter("LEGALCASE", typeof(string));
    
            var eXPENSE_APPROVE_FLAGParameter = eXPENSE_APPROVE_FLAG != null ?
                new ObjectParameter("EXPENSE_APPROVE_FLAG", eXPENSE_APPROVE_FLAG) :
                new ObjectParameter("EXPENSE_APPROVE_FLAG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_COURTFEES_Result>("SP_SEARCH_COURTFEES", rEF_NOParameter, cONTRACT_NOParameter, pAYMENTNOFROMParameter, pAYMENTNOTOParameter, pAYMENTDATEFROMParameter, pAYMENTDATETOParameter, aDMIN_CODEParameter, oA_CODEParameter, lEGALCASEParameter, eXPENSE_APPROVE_FLAGParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_CUSTOMER_Result> SP_SEARCH_CUSTOMER(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_CUSTOMER_Result>("SP_SEARCH_CUSTOMER", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_DOCUMENT_BY_CASE_Result> SP_SEARCH_DOCUMENT_BY_CASE(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_DOCUMENT_BY_CASE_Result>("SP_SEARCH_DOCUMENT_BY_CASE", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_DOCUMENT_BY_REF_Result> SP_SEARCH_DOCUMENT_BY_REF(string jOB_ID, string cASE_CODE)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            var cASE_CODEParameter = cASE_CODE != null ?
                new ObjectParameter("CASE_CODE", cASE_CODE) :
                new ObjectParameter("CASE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_DOCUMENT_BY_REF_Result>("SP_SEARCH_DOCUMENT_BY_REF", jOB_IDParameter, cASE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_EXPENSE_Result> SP_SEARCH_EXPENSE(string rEF_NO, string cONTRACT_NO, string pAYMENTNOFROM, string pAYMENTNOTO, Nullable<System.DateTime> pAYMENTDATEFROM, Nullable<System.DateTime> pAYMENTDATETO, string aDMIN_CODE, string oA_CODE, string lEGALCASE, string eXPENSE_APPROVE_FLAG)
        {
            var rEF_NOParameter = rEF_NO != null ?
                new ObjectParameter("REF_NO", rEF_NO) :
                new ObjectParameter("REF_NO", typeof(string));
    
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var pAYMENTNOFROMParameter = pAYMENTNOFROM != null ?
                new ObjectParameter("PAYMENTNOFROM", pAYMENTNOFROM) :
                new ObjectParameter("PAYMENTNOFROM", typeof(string));
    
            var pAYMENTNOTOParameter = pAYMENTNOTO != null ?
                new ObjectParameter("PAYMENTNOTO", pAYMENTNOTO) :
                new ObjectParameter("PAYMENTNOTO", typeof(string));
    
            var pAYMENTDATEFROMParameter = pAYMENTDATEFROM.HasValue ?
                new ObjectParameter("PAYMENTDATEFROM", pAYMENTDATEFROM) :
                new ObjectParameter("PAYMENTDATEFROM", typeof(System.DateTime));
    
            var pAYMENTDATETOParameter = pAYMENTDATETO.HasValue ?
                new ObjectParameter("PAYMENTDATETO", pAYMENTDATETO) :
                new ObjectParameter("PAYMENTDATETO", typeof(System.DateTime));
    
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var oA_CODEParameter = oA_CODE != null ?
                new ObjectParameter("OA_CODE", oA_CODE) :
                new ObjectParameter("OA_CODE", typeof(string));
    
            var lEGALCASEParameter = lEGALCASE != null ?
                new ObjectParameter("LEGALCASE", lEGALCASE) :
                new ObjectParameter("LEGALCASE", typeof(string));
    
            var eXPENSE_APPROVE_FLAGParameter = eXPENSE_APPROVE_FLAG != null ?
                new ObjectParameter("EXPENSE_APPROVE_FLAG", eXPENSE_APPROVE_FLAG) :
                new ObjectParameter("EXPENSE_APPROVE_FLAG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_EXPENSE_Result>("SP_SEARCH_EXPENSE", rEF_NOParameter, cONTRACT_NOParameter, pAYMENTNOFROMParameter, pAYMENTNOTOParameter, pAYMENTDATEFROMParameter, pAYMENTDATETOParameter, aDMIN_CODEParameter, oA_CODEParameter, lEGALCASEParameter, eXPENSE_APPROVE_FLAGParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_EXPENSE_CONFIG_Result> SP_SEARCH_EXPENSE_CONFIG(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_EXPENSE_CONFIG_Result>("SP_SEARCH_EXPENSE_CONFIG", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_EXPENSE_DETAIL_Result> SP_SEARCH_EXPENSE_DETAIL(string eXPEN_ID)
        {
            var eXPEN_IDParameter = eXPEN_ID != null ?
                new ObjectParameter("EXPEN_ID", eXPEN_ID) :
                new ObjectParameter("EXPEN_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_EXPENSE_DETAIL_Result>("SP_SEARCH_EXPENSE_DETAIL", eXPEN_IDParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_FRAUD_BY_DOC_Result> SP_SEARCH_FRAUD_BY_DOC(string dOC_NO)
        {
            var dOC_NOParameter = dOC_NO != null ?
                new ObjectParameter("DOC_NO", dOC_NO) :
                new ObjectParameter("DOC_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_FRAUD_BY_DOC_Result>("SP_SEARCH_FRAUD_BY_DOC", dOC_NOParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_JOB_Result> SP_SEARCH_JOB(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_JOB_Result>("SP_SEARCH_JOB", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_JUDGMENTDEBTOR_Result> SP_SEARCH_JUDGMENTDEBTOR(string jOB_ID, string contractNo, string custName, Nullable<System.DateTime> judgmentDateFrom, Nullable<System.DateTime> judgmentDateTo, Nullable<System.DateTime> compromiseDateFrom, Nullable<System.DateTime> compromiseDateTo, string redCode, string admin, string legalCase, string legalOA, string debtorStatus, string approveStatus, string activeStatus)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            var contractNoParameter = contractNo != null ?
                new ObjectParameter("ContractNo", contractNo) :
                new ObjectParameter("ContractNo", typeof(string));
    
            var custNameParameter = custName != null ?
                new ObjectParameter("CustName", custName) :
                new ObjectParameter("CustName", typeof(string));
    
            var judgmentDateFromParameter = judgmentDateFrom.HasValue ?
                new ObjectParameter("JudgmentDateFrom", judgmentDateFrom) :
                new ObjectParameter("JudgmentDateFrom", typeof(System.DateTime));
    
            var judgmentDateToParameter = judgmentDateTo.HasValue ?
                new ObjectParameter("JudgmentDateTo", judgmentDateTo) :
                new ObjectParameter("JudgmentDateTo", typeof(System.DateTime));
    
            var compromiseDateFromParameter = compromiseDateFrom.HasValue ?
                new ObjectParameter("CompromiseDateFrom", compromiseDateFrom) :
                new ObjectParameter("CompromiseDateFrom", typeof(System.DateTime));
    
            var compromiseDateToParameter = compromiseDateTo.HasValue ?
                new ObjectParameter("CompromiseDateTo", compromiseDateTo) :
                new ObjectParameter("CompromiseDateTo", typeof(System.DateTime));
    
            var redCodeParameter = redCode != null ?
                new ObjectParameter("RedCode", redCode) :
                new ObjectParameter("RedCode", typeof(string));
    
            var adminParameter = admin != null ?
                new ObjectParameter("Admin", admin) :
                new ObjectParameter("Admin", typeof(string));
    
            var legalCaseParameter = legalCase != null ?
                new ObjectParameter("LegalCase", legalCase) :
                new ObjectParameter("LegalCase", typeof(string));
    
            var legalOAParameter = legalOA != null ?
                new ObjectParameter("LegalOA", legalOA) :
                new ObjectParameter("LegalOA", typeof(string));
    
            var debtorStatusParameter = debtorStatus != null ?
                new ObjectParameter("DebtorStatus", debtorStatus) :
                new ObjectParameter("DebtorStatus", typeof(string));
    
            var approveStatusParameter = approveStatus != null ?
                new ObjectParameter("ApproveStatus", approveStatus) :
                new ObjectParameter("ApproveStatus", typeof(string));
    
            var activeStatusParameter = activeStatus != null ?
                new ObjectParameter("ActiveStatus", activeStatus) :
                new ObjectParameter("ActiveStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_JUDGMENTDEBTOR_Result>("SP_SEARCH_JUDGMENTDEBTOR", jOB_IDParameter, contractNoParameter, custNameParameter, judgmentDateFromParameter, judgmentDateToParameter, compromiseDateFromParameter, compromiseDateToParameter, redCodeParameter, adminParameter, legalCaseParameter, legalOAParameter, debtorStatusParameter, approveStatusParameter, activeStatusParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_JUDGMENTDEBTOR_CHEQUE_Result> SP_SEARCH_JUDGMENTDEBTOR_CHEQUE(string jOB_ID, string cheque, string custName, Nullable<System.DateTime> judgmentDateFrom, Nullable<System.DateTime> judgmentDateTo, Nullable<System.DateTime> compromiseDateFrom, Nullable<System.DateTime> compromiseDateTo, string redCode, string admin, string legalCase, string legalOA, string debtorStatus, string approveStatus, string activeStatus)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            var chequeParameter = cheque != null ?
                new ObjectParameter("Cheque", cheque) :
                new ObjectParameter("Cheque", typeof(string));
    
            var custNameParameter = custName != null ?
                new ObjectParameter("CustName", custName) :
                new ObjectParameter("CustName", typeof(string));
    
            var judgmentDateFromParameter = judgmentDateFrom.HasValue ?
                new ObjectParameter("JudgmentDateFrom", judgmentDateFrom) :
                new ObjectParameter("JudgmentDateFrom", typeof(System.DateTime));
    
            var judgmentDateToParameter = judgmentDateTo.HasValue ?
                new ObjectParameter("JudgmentDateTo", judgmentDateTo) :
                new ObjectParameter("JudgmentDateTo", typeof(System.DateTime));
    
            var compromiseDateFromParameter = compromiseDateFrom.HasValue ?
                new ObjectParameter("CompromiseDateFrom", compromiseDateFrom) :
                new ObjectParameter("CompromiseDateFrom", typeof(System.DateTime));
    
            var compromiseDateToParameter = compromiseDateTo.HasValue ?
                new ObjectParameter("CompromiseDateTo", compromiseDateTo) :
                new ObjectParameter("CompromiseDateTo", typeof(System.DateTime));
    
            var redCodeParameter = redCode != null ?
                new ObjectParameter("RedCode", redCode) :
                new ObjectParameter("RedCode", typeof(string));
    
            var adminParameter = admin != null ?
                new ObjectParameter("Admin", admin) :
                new ObjectParameter("Admin", typeof(string));
    
            var legalCaseParameter = legalCase != null ?
                new ObjectParameter("LegalCase", legalCase) :
                new ObjectParameter("LegalCase", typeof(string));
    
            var legalOAParameter = legalOA != null ?
                new ObjectParameter("LegalOA", legalOA) :
                new ObjectParameter("LegalOA", typeof(string));
    
            var debtorStatusParameter = debtorStatus != null ?
                new ObjectParameter("DebtorStatus", debtorStatus) :
                new ObjectParameter("DebtorStatus", typeof(string));
    
            var approveStatusParameter = approveStatus != null ?
                new ObjectParameter("ApproveStatus", approveStatus) :
                new ObjectParameter("ApproveStatus", typeof(string));
    
            var activeStatusParameter = activeStatus != null ?
                new ObjectParameter("ActiveStatus", activeStatus) :
                new ObjectParameter("ActiveStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_JUDGMENTDEBTOR_CHEQUE_Result>("SP_SEARCH_JUDGMENTDEBTOR_CHEQUE", jOB_IDParameter, chequeParameter, custNameParameter, judgmentDateFromParameter, judgmentDateToParameter, compromiseDateFromParameter, compromiseDateToParameter, redCodeParameter, adminParameter, legalCaseParameter, legalOAParameter, debtorStatusParameter, approveStatusParameter, activeStatusParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_MAPPING_OA_Result> SP_SEARCH_MAPPING_OA(string oACode, string bucketCode)
        {
            var oACodeParameter = oACode != null ?
                new ObjectParameter("OACode", oACode) :
                new ObjectParameter("OACode", typeof(string));
    
            var bucketCodeParameter = bucketCode != null ?
                new ObjectParameter("BucketCode", bucketCode) :
                new ObjectParameter("BucketCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_MAPPING_OA_Result>("SP_SEARCH_MAPPING_OA", oACodeParameter, bucketCodeParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_PERMISSION_BY_ROLE_Result> SP_SEARCH_PERMISSION_BY_ROLE(string rOLE_CODE)
        {
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_PERMISSION_BY_ROLE_Result>("SP_SEARCH_PERMISSION_BY_ROLE", rOLE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_R3_Result> SP_SEARCH_R3(string cONTRACT_NO, string sTATUS, string sTATUSDATA, string cUST_NAME, Nullable<System.DateTime> iSSUE_DATE_FROM, Nullable<System.DateTime> iSSUE_DATE_TO, Nullable<System.DateTime> sEND_DATE_FROM, Nullable<System.DateTime> sEND_DATE_TO, Nullable<System.DateTime> rECEIVE_YELLOW_DATE_FROM, Nullable<System.DateTime> rECEIVE_YELLOW_DATE_TO, string aDMIN_CODE, string rOLE_CODE)
        {
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var sTATUSDATAParameter = sTATUSDATA != null ?
                new ObjectParameter("STATUSDATA", sTATUSDATA) :
                new ObjectParameter("STATUSDATA", typeof(string));
    
            var cUST_NAMEParameter = cUST_NAME != null ?
                new ObjectParameter("CUST_NAME", cUST_NAME) :
                new ObjectParameter("CUST_NAME", typeof(string));
    
            var iSSUE_DATE_FROMParameter = iSSUE_DATE_FROM.HasValue ?
                new ObjectParameter("ISSUE_DATE_FROM", iSSUE_DATE_FROM) :
                new ObjectParameter("ISSUE_DATE_FROM", typeof(System.DateTime));
    
            var iSSUE_DATE_TOParameter = iSSUE_DATE_TO.HasValue ?
                new ObjectParameter("ISSUE_DATE_TO", iSSUE_DATE_TO) :
                new ObjectParameter("ISSUE_DATE_TO", typeof(System.DateTime));
    
            var sEND_DATE_FROMParameter = sEND_DATE_FROM.HasValue ?
                new ObjectParameter("SEND_DATE_FROM", sEND_DATE_FROM) :
                new ObjectParameter("SEND_DATE_FROM", typeof(System.DateTime));
    
            var sEND_DATE_TOParameter = sEND_DATE_TO.HasValue ?
                new ObjectParameter("SEND_DATE_TO", sEND_DATE_TO) :
                new ObjectParameter("SEND_DATE_TO", typeof(System.DateTime));
    
            var rECEIVE_YELLOW_DATE_FROMParameter = rECEIVE_YELLOW_DATE_FROM.HasValue ?
                new ObjectParameter("RECEIVE_YELLOW_DATE_FROM", rECEIVE_YELLOW_DATE_FROM) :
                new ObjectParameter("RECEIVE_YELLOW_DATE_FROM", typeof(System.DateTime));
    
            var rECEIVE_YELLOW_DATE_TOParameter = rECEIVE_YELLOW_DATE_TO.HasValue ?
                new ObjectParameter("RECEIVE_YELLOW_DATE_TO", rECEIVE_YELLOW_DATE_TO) :
                new ObjectParameter("RECEIVE_YELLOW_DATE_TO", typeof(System.DateTime));
    
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_R3_Result>("SP_SEARCH_R3", cONTRACT_NOParameter, sTATUSParameter, sTATUSDATAParameter, cUST_NAMEParameter, iSSUE_DATE_FROMParameter, iSSUE_DATE_TOParameter, sEND_DATE_FROMParameter, sEND_DATE_TOParameter, rECEIVE_YELLOW_DATE_FROMParameter, rECEIVE_YELLOW_DATE_TOParameter, aDMIN_CODEParameter, rOLE_CODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_RC_Result> SP_SEARCH_RC(string rEF_NO, string cONTRACT_NO, string cUST_NAME, string sTATUS, string aDMIN, string oA_CODE, Nullable<System.DateTime> aSSIGN_DATE_FROM, Nullable<System.DateTime> aSSIGN_DATE_TO, string aDMIN_CODE, string rOLE_CODE, string dATASTATUS)
        {
            var rEF_NOParameter = rEF_NO != null ?
                new ObjectParameter("REF_NO", rEF_NO) :
                new ObjectParameter("REF_NO", typeof(string));
    
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var cUST_NAMEParameter = cUST_NAME != null ?
                new ObjectParameter("CUST_NAME", cUST_NAME) :
                new ObjectParameter("CUST_NAME", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var aDMINParameter = aDMIN != null ?
                new ObjectParameter("ADMIN", aDMIN) :
                new ObjectParameter("ADMIN", typeof(string));
    
            var oA_CODEParameter = oA_CODE != null ?
                new ObjectParameter("OA_CODE", oA_CODE) :
                new ObjectParameter("OA_CODE", typeof(string));
    
            var aSSIGN_DATE_FROMParameter = aSSIGN_DATE_FROM.HasValue ?
                new ObjectParameter("ASSIGN_DATE_FROM", aSSIGN_DATE_FROM) :
                new ObjectParameter("ASSIGN_DATE_FROM", typeof(System.DateTime));
    
            var aSSIGN_DATE_TOParameter = aSSIGN_DATE_TO.HasValue ?
                new ObjectParameter("ASSIGN_DATE_TO", aSSIGN_DATE_TO) :
                new ObjectParameter("ASSIGN_DATE_TO", typeof(System.DateTime));
    
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            var dATASTATUSParameter = dATASTATUS != null ?
                new ObjectParameter("DATASTATUS", dATASTATUS) :
                new ObjectParameter("DATASTATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_RC_Result>("SP_SEARCH_RC", rEF_NOParameter, cONTRACT_NOParameter, cUST_NAMEParameter, sTATUSParameter, aDMINParameter, oA_CODEParameter, aSSIGN_DATE_FROMParameter, aSSIGN_DATE_TOParameter, aDMIN_CODEParameter, rOLE_CODEParameter, dATASTATUSParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_SPECIAL_CASE_Result> SP_SEARCH_SPECIAL_CASE(string cONTRACT_NO, string cHEQUE_NO, string aDMIN, string lEGAL_OA, string rEF_NO, string cASE_TYPE, string lEGAL_CASE, string sTATUS)
        {
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var cHEQUE_NOParameter = cHEQUE_NO != null ?
                new ObjectParameter("CHEQUE_NO", cHEQUE_NO) :
                new ObjectParameter("CHEQUE_NO", typeof(string));
    
            var aDMINParameter = aDMIN != null ?
                new ObjectParameter("ADMIN", aDMIN) :
                new ObjectParameter("ADMIN", typeof(string));
    
            var lEGAL_OAParameter = lEGAL_OA != null ?
                new ObjectParameter("LEGAL_OA", lEGAL_OA) :
                new ObjectParameter("LEGAL_OA", typeof(string));
    
            var rEF_NOParameter = rEF_NO != null ?
                new ObjectParameter("REF_NO", rEF_NO) :
                new ObjectParameter("REF_NO", typeof(string));
    
            var cASE_TYPEParameter = cASE_TYPE != null ?
                new ObjectParameter("CASE_TYPE", cASE_TYPE) :
                new ObjectParameter("CASE_TYPE", typeof(string));
    
            var lEGAL_CASEParameter = lEGAL_CASE != null ?
                new ObjectParameter("LEGAL_CASE", lEGAL_CASE) :
                new ObjectParameter("LEGAL_CASE", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_SPECIAL_CASE_Result>("SP_SEARCH_SPECIAL_CASE", cONTRACT_NOParameter, cHEQUE_NOParameter, aDMINParameter, lEGAL_OAParameter, rEF_NOParameter, cASE_TYPEParameter, lEGAL_CASEParameter, sTATUSParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_SPECIAL_CASE_CHEQUE_LIST_Result> SP_SEARCH_SPECIAL_CASE_CHEQUE_LIST(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_SPECIAL_CASE_CHEQUE_LIST_Result>("SP_SEARCH_SPECIAL_CASE_CHEQUE_LIST", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_STATUS_BY_CASE_Result> SP_SEARCH_STATUS_BY_CASE(string sEARCH)
        {
            var sEARCHParameter = sEARCH != null ?
                new ObjectParameter("SEARCH", sEARCH) :
                new ObjectParameter("SEARCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_STATUS_BY_CASE_Result>("SP_SEARCH_STATUS_BY_CASE", sEARCHParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_SUGGEST_WRITEOFF_BY_DOC_Result> SP_SEARCH_SUGGEST_WRITEOFF_BY_DOC(string dOC_NO)
        {
            var dOC_NOParameter = dOC_NO != null ?
                new ObjectParameter("DOC_NO", dOC_NO) :
                new ObjectParameter("DOC_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_SUGGEST_WRITEOFF_BY_DOC_Result>("SP_SEARCH_SUGGEST_WRITEOFF_BY_DOC", dOC_NOParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_TODOLIST_Result> SP_SEARCH_TODOLIST(string rEF_NO, string cONTRACT_NO, string cUST_CODE, string cASE_CODE, string cASE_STATUS, string tRAFFIC_CODE, string aDMIN_CODE, string oA_CODE, Nullable<System.DateTime> aSSIGN_ADMIN_DATE_START, Nullable<System.DateTime> aSSIGN_ADMIN_DATE_END, Nullable<System.DateTime> aSSIGN_OA_DATE_START, Nullable<System.DateTime> aSSIGN_OA_DATE_END, string sUCC_STATUS, string rOLE_CODE, string mODE)
        {
            var rEF_NOParameter = rEF_NO != null ?
                new ObjectParameter("REF_NO", rEF_NO) :
                new ObjectParameter("REF_NO", typeof(string));
    
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var cUST_CODEParameter = cUST_CODE != null ?
                new ObjectParameter("CUST_CODE", cUST_CODE) :
                new ObjectParameter("CUST_CODE", typeof(string));
    
            var cASE_CODEParameter = cASE_CODE != null ?
                new ObjectParameter("CASE_CODE", cASE_CODE) :
                new ObjectParameter("CASE_CODE", typeof(string));
    
            var cASE_STATUSParameter = cASE_STATUS != null ?
                new ObjectParameter("CASE_STATUS", cASE_STATUS) :
                new ObjectParameter("CASE_STATUS", typeof(string));
    
            var tRAFFIC_CODEParameter = tRAFFIC_CODE != null ?
                new ObjectParameter("TRAFFIC_CODE", tRAFFIC_CODE) :
                new ObjectParameter("TRAFFIC_CODE", typeof(string));
    
            var aDMIN_CODEParameter = aDMIN_CODE != null ?
                new ObjectParameter("ADMIN_CODE", aDMIN_CODE) :
                new ObjectParameter("ADMIN_CODE", typeof(string));
    
            var oA_CODEParameter = oA_CODE != null ?
                new ObjectParameter("OA_CODE", oA_CODE) :
                new ObjectParameter("OA_CODE", typeof(string));
    
            var aSSIGN_ADMIN_DATE_STARTParameter = aSSIGN_ADMIN_DATE_START.HasValue ?
                new ObjectParameter("ASSIGN_ADMIN_DATE_START", aSSIGN_ADMIN_DATE_START) :
                new ObjectParameter("ASSIGN_ADMIN_DATE_START", typeof(System.DateTime));
    
            var aSSIGN_ADMIN_DATE_ENDParameter = aSSIGN_ADMIN_DATE_END.HasValue ?
                new ObjectParameter("ASSIGN_ADMIN_DATE_END", aSSIGN_ADMIN_DATE_END) :
                new ObjectParameter("ASSIGN_ADMIN_DATE_END", typeof(System.DateTime));
    
            var aSSIGN_OA_DATE_STARTParameter = aSSIGN_OA_DATE_START.HasValue ?
                new ObjectParameter("ASSIGN_OA_DATE_START", aSSIGN_OA_DATE_START) :
                new ObjectParameter("ASSIGN_OA_DATE_START", typeof(System.DateTime));
    
            var aSSIGN_OA_DATE_ENDParameter = aSSIGN_OA_DATE_END.HasValue ?
                new ObjectParameter("ASSIGN_OA_DATE_END", aSSIGN_OA_DATE_END) :
                new ObjectParameter("ASSIGN_OA_DATE_END", typeof(System.DateTime));
    
            var sUCC_STATUSParameter = sUCC_STATUS != null ?
                new ObjectParameter("SUCC_STATUS", sUCC_STATUS) :
                new ObjectParameter("SUCC_STATUS", typeof(string));
    
            var rOLE_CODEParameter = rOLE_CODE != null ?
                new ObjectParameter("ROLE_CODE", rOLE_CODE) :
                new ObjectParameter("ROLE_CODE", typeof(string));
    
            var mODEParameter = mODE != null ?
                new ObjectParameter("MODE", mODE) :
                new ObjectParameter("MODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_TODOLIST_Result>("SP_SEARCH_TODOLIST", rEF_NOParameter, cONTRACT_NOParameter, cUST_CODEParameter, cASE_CODEParameter, cASE_STATUSParameter, tRAFFIC_CODEParameter, aDMIN_CODEParameter, oA_CODEParameter, aSSIGN_ADMIN_DATE_STARTParameter, aSSIGN_ADMIN_DATE_ENDParameter, aSSIGN_OA_DATE_STARTParameter, aSSIGN_OA_DATE_ENDParameter, sUCC_STATUSParameter, rOLE_CODEParameter, mODEParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_WRITE_OFF_Result> SP_SEARCH_WRITE_OFF(string cONTRACT_NO, Nullable<decimal> oS_START, Nullable<decimal> oS_END, string r3_STATUS, string rEPO_STATUS, string aUCTION_STATUS, string lEGAL_CASE, string lEGAL_STATUS, Nullable<decimal> dUE_STATRT, Nullable<decimal> dUE_END, Nullable<System.DateTime> fILING_DATE_START, Nullable<System.DateTime> fILING_DATE_END, Nullable<System.DateTime> jUDGMENT_DATE_START, Nullable<System.DateTime> jUDGMENT_DATE_END, Nullable<System.DateTime> eN_DATE_START, Nullable<System.DateTime> eN_DATE_END, Nullable<System.DateTime> sUBMIT_INVERT_DATE_START, Nullable<System.DateTime> sUBMIT_INVERT_DATE_END, Nullable<System.DateTime> rEPORT_DATE_START, Nullable<System.DateTime> rEPORT_DATE_END, Nullable<System.DateTime> eXECUTION_DATE_START, Nullable<System.DateTime> eXECUTION_DATE_END, Nullable<System.DateTime> eXECUTION_END_DATE_START, Nullable<System.DateTime> eXECUTION_END_DATE_END, Nullable<System.DateTime> sUBMIT_EN_DATE_START, Nullable<System.DateTime> sUBMIT_EN_DATE_END)
        {
            var cONTRACT_NOParameter = cONTRACT_NO != null ?
                new ObjectParameter("CONTRACT_NO", cONTRACT_NO) :
                new ObjectParameter("CONTRACT_NO", typeof(string));
    
            var oS_STARTParameter = oS_START.HasValue ?
                new ObjectParameter("OS_START", oS_START) :
                new ObjectParameter("OS_START", typeof(decimal));
    
            var oS_ENDParameter = oS_END.HasValue ?
                new ObjectParameter("OS_END", oS_END) :
                new ObjectParameter("OS_END", typeof(decimal));
    
            var r3_STATUSParameter = r3_STATUS != null ?
                new ObjectParameter("R3_STATUS", r3_STATUS) :
                new ObjectParameter("R3_STATUS", typeof(string));
    
            var rEPO_STATUSParameter = rEPO_STATUS != null ?
                new ObjectParameter("REPO_STATUS", rEPO_STATUS) :
                new ObjectParameter("REPO_STATUS", typeof(string));
    
            var aUCTION_STATUSParameter = aUCTION_STATUS != null ?
                new ObjectParameter("AUCTION_STATUS", aUCTION_STATUS) :
                new ObjectParameter("AUCTION_STATUS", typeof(string));
    
            var lEGAL_CASEParameter = lEGAL_CASE != null ?
                new ObjectParameter("LEGAL_CASE", lEGAL_CASE) :
                new ObjectParameter("LEGAL_CASE", typeof(string));
    
            var lEGAL_STATUSParameter = lEGAL_STATUS != null ?
                new ObjectParameter("LEGAL_STATUS", lEGAL_STATUS) :
                new ObjectParameter("LEGAL_STATUS", typeof(string));
    
            var dUE_STATRTParameter = dUE_STATRT.HasValue ?
                new ObjectParameter("DUE_STATRT", dUE_STATRT) :
                new ObjectParameter("DUE_STATRT", typeof(decimal));
    
            var dUE_ENDParameter = dUE_END.HasValue ?
                new ObjectParameter("DUE_END", dUE_END) :
                new ObjectParameter("DUE_END", typeof(decimal));
    
            var fILING_DATE_STARTParameter = fILING_DATE_START.HasValue ?
                new ObjectParameter("FILING_DATE_START", fILING_DATE_START) :
                new ObjectParameter("FILING_DATE_START", typeof(System.DateTime));
    
            var fILING_DATE_ENDParameter = fILING_DATE_END.HasValue ?
                new ObjectParameter("FILING_DATE_END", fILING_DATE_END) :
                new ObjectParameter("FILING_DATE_END", typeof(System.DateTime));
    
            var jUDGMENT_DATE_STARTParameter = jUDGMENT_DATE_START.HasValue ?
                new ObjectParameter("JUDGMENT_DATE_START", jUDGMENT_DATE_START) :
                new ObjectParameter("JUDGMENT_DATE_START", typeof(System.DateTime));
    
            var jUDGMENT_DATE_ENDParameter = jUDGMENT_DATE_END.HasValue ?
                new ObjectParameter("JUDGMENT_DATE_END", jUDGMENT_DATE_END) :
                new ObjectParameter("JUDGMENT_DATE_END", typeof(System.DateTime));
    
            var eN_DATE_STARTParameter = eN_DATE_START.HasValue ?
                new ObjectParameter("EN_DATE_START", eN_DATE_START) :
                new ObjectParameter("EN_DATE_START", typeof(System.DateTime));
    
            var eN_DATE_ENDParameter = eN_DATE_END.HasValue ?
                new ObjectParameter("EN_DATE_END", eN_DATE_END) :
                new ObjectParameter("EN_DATE_END", typeof(System.DateTime));
    
            var sUBMIT_INVERT_DATE_STARTParameter = sUBMIT_INVERT_DATE_START.HasValue ?
                new ObjectParameter("SUBMIT_INVERT_DATE_START", sUBMIT_INVERT_DATE_START) :
                new ObjectParameter("SUBMIT_INVERT_DATE_START", typeof(System.DateTime));
    
            var sUBMIT_INVERT_DATE_ENDParameter = sUBMIT_INVERT_DATE_END.HasValue ?
                new ObjectParameter("SUBMIT_INVERT_DATE_END", sUBMIT_INVERT_DATE_END) :
                new ObjectParameter("SUBMIT_INVERT_DATE_END", typeof(System.DateTime));
    
            var rEPORT_DATE_STARTParameter = rEPORT_DATE_START.HasValue ?
                new ObjectParameter("REPORT_DATE_START", rEPORT_DATE_START) :
                new ObjectParameter("REPORT_DATE_START", typeof(System.DateTime));
    
            var rEPORT_DATE_ENDParameter = rEPORT_DATE_END.HasValue ?
                new ObjectParameter("REPORT_DATE_END", rEPORT_DATE_END) :
                new ObjectParameter("REPORT_DATE_END", typeof(System.DateTime));
    
            var eXECUTION_DATE_STARTParameter = eXECUTION_DATE_START.HasValue ?
                new ObjectParameter("EXECUTION_DATE_START", eXECUTION_DATE_START) :
                new ObjectParameter("EXECUTION_DATE_START", typeof(System.DateTime));
    
            var eXECUTION_DATE_ENDParameter = eXECUTION_DATE_END.HasValue ?
                new ObjectParameter("EXECUTION_DATE_END", eXECUTION_DATE_END) :
                new ObjectParameter("EXECUTION_DATE_END", typeof(System.DateTime));
    
            var eXECUTION_END_DATE_STARTParameter = eXECUTION_END_DATE_START.HasValue ?
                new ObjectParameter("EXECUTION_END_DATE_START", eXECUTION_END_DATE_START) :
                new ObjectParameter("EXECUTION_END_DATE_START", typeof(System.DateTime));
    
            var eXECUTION_END_DATE_ENDParameter = eXECUTION_END_DATE_END.HasValue ?
                new ObjectParameter("EXECUTION_END_DATE_END", eXECUTION_END_DATE_END) :
                new ObjectParameter("EXECUTION_END_DATE_END", typeof(System.DateTime));
    
            var sUBMIT_EN_DATE_STARTParameter = sUBMIT_EN_DATE_START.HasValue ?
                new ObjectParameter("SUBMIT_EN_DATE_START", sUBMIT_EN_DATE_START) :
                new ObjectParameter("SUBMIT_EN_DATE_START", typeof(System.DateTime));
    
            var sUBMIT_EN_DATE_ENDParameter = sUBMIT_EN_DATE_END.HasValue ?
                new ObjectParameter("SUBMIT_EN_DATE_END", sUBMIT_EN_DATE_END) :
                new ObjectParameter("SUBMIT_EN_DATE_END", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_WRITE_OFF_Result>("SP_SEARCH_WRITE_OFF", cONTRACT_NOParameter, oS_STARTParameter, oS_ENDParameter, r3_STATUSParameter, rEPO_STATUSParameter, aUCTION_STATUSParameter, lEGAL_CASEParameter, lEGAL_STATUSParameter, dUE_STATRTParameter, dUE_ENDParameter, fILING_DATE_STARTParameter, fILING_DATE_ENDParameter, jUDGMENT_DATE_STARTParameter, jUDGMENT_DATE_ENDParameter, eN_DATE_STARTParameter, eN_DATE_ENDParameter, sUBMIT_INVERT_DATE_STARTParameter, sUBMIT_INVERT_DATE_ENDParameter, rEPORT_DATE_STARTParameter, rEPORT_DATE_ENDParameter, eXECUTION_DATE_STARTParameter, eXECUTION_DATE_ENDParameter, eXECUTION_END_DATE_STARTParameter, eXECUTION_END_DATE_ENDParameter, sUBMIT_EN_DATE_STARTParameter, sUBMIT_EN_DATE_ENDParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_WRITE_OFF_ALL_Result> SP_SEARCH_WRITE_OFF_ALL(string wF_STATUS)
        {
            var wF_STATUSParameter = wF_STATUS != null ?
                new ObjectParameter("WF_STATUS", wF_STATUS) :
                new ObjectParameter("WF_STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_WRITE_OFF_ALL_Result>("SP_SEARCH_WRITE_OFF_ALL", wF_STATUSParameter);
        }
    
        public virtual ObjectResult<SP_SEARCH_WRITE_OFF_VIEW_DOC_Result> SP_SEARCH_WRITE_OFF_VIEW_DOC(Nullable<System.DateTime> aPPROVE_DATE_FROM, Nullable<System.DateTime> aPPROVE_DATE_TO, string aPPROVE_STATUS)
        {
            var aPPROVE_DATE_FROMParameter = aPPROVE_DATE_FROM.HasValue ?
                new ObjectParameter("APPROVE_DATE_FROM", aPPROVE_DATE_FROM) :
                new ObjectParameter("APPROVE_DATE_FROM", typeof(System.DateTime));
    
            var aPPROVE_DATE_TOParameter = aPPROVE_DATE_TO.HasValue ?
                new ObjectParameter("APPROVE_DATE_TO", aPPROVE_DATE_TO) :
                new ObjectParameter("APPROVE_DATE_TO", typeof(System.DateTime));
    
            var aPPROVE_STATUSParameter = aPPROVE_STATUS != null ?
                new ObjectParameter("APPROVE_STATUS", aPPROVE_STATUS) :
                new ObjectParameter("APPROVE_STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEARCH_WRITE_OFF_VIEW_DOC_Result>("SP_SEARCH_WRITE_OFF_VIEW_DOC", aPPROVE_DATE_FROMParameter, aPPROVE_DATE_TOParameter, aPPROVE_STATUSParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_JUDGMENT_DEBTOR_BY_JD_ID_Result> SP_SELECT_JUDGMENT_DEBTOR_BY_JD_ID(string jD_ID)
        {
            var jD_IDParameter = jD_ID != null ?
                new ObjectParameter("JD_ID", jD_ID) :
                new ObjectParameter("JD_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_JUDGMENT_DEBTOR_BY_JD_ID_Result>("SP_SELECT_JUDGMENT_DEBTOR_BY_JD_ID", jD_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_JUDGMENT_DEBTOR_BY_JOB_Result> SP_SELECT_JUDGMENT_DEBTOR_BY_JOB(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_JUDGMENT_DEBTOR_BY_JOB_Result>("SP_SELECT_JUDGMENT_DEBTOR_BY_JOB", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_JUDGMENT_DEBTOR_BY_JOB_ID_Result> SP_SELECT_JUDGMENT_DEBTOR_BY_JOB_ID(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_JUDGMENT_DEBTOR_BY_JOB_ID_Result>("SP_SELECT_JUDGMENT_DEBTOR_BY_JOB_ID", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_JUDGMENT_DEBTOR_DETAIL_BY_JOB_Result> SP_SELECT_JUDGMENT_DEBTOR_DETAIL_BY_JOB(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_JUDGMENT_DEBTOR_DETAIL_BY_JOB_Result>("SP_SELECT_JUDGMENT_DEBTOR_DETAIL_BY_JOB", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_LEGAL_ATTACH_BY_JOB_Result> SP_SELECT_LEGAL_ATTACH_BY_JOB(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_LEGAL_ATTACH_BY_JOB_Result>("SP_SELECT_LEGAL_ATTACH_BY_JOB", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_LEGAL_CAR_RECEIVE_BY_JOB_Result> SP_SELECT_LEGAL_CAR_RECEIVE_BY_JOB(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_LEGAL_CAR_RECEIVE_BY_JOB_Result>("SP_SELECT_LEGAL_CAR_RECEIVE_BY_JOB", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_LEGAL_CASE_BY_JOB_Result> SP_SELECT_LEGAL_CASE_BY_JOB(string jOB_ID, string jOB_CONTRACT_NO)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            var jOB_CONTRACT_NOParameter = jOB_CONTRACT_NO != null ?
                new ObjectParameter("JOB_CONTRACT_NO", jOB_CONTRACT_NO) :
                new ObjectParameter("JOB_CONTRACT_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_LEGAL_CASE_BY_JOB_Result>("SP_SELECT_LEGAL_CASE_BY_JOB", jOB_IDParameter, jOB_CONTRACT_NOParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_LEGAL_COURT_FEE_BY_JOB_Result> SP_SELECT_LEGAL_COURT_FEE_BY_JOB(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_LEGAL_COURT_FEE_BY_JOB_Result>("SP_SELECT_LEGAL_COURT_FEE_BY_JOB", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_LEGAL_DEBTOR_EXPENSE_BY_JOB_Result> SP_SELECT_LEGAL_DEBTOR_EXPENSE_BY_JOB(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_LEGAL_DEBTOR_EXPENSE_BY_JOB_Result>("SP_SELECT_LEGAL_DEBTOR_EXPENSE_BY_JOB", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_LEGAL_EXPENSE_BY_JOB_Result> SP_SELECT_LEGAL_EXPENSE_BY_JOB(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_LEGAL_EXPENSE_BY_JOB_Result>("SP_SELECT_LEGAL_EXPENSE_BY_JOB", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_LEGAL_REPO_BY_JOB_Result> SP_SELECT_LEGAL_REPO_BY_JOB(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_LEGAL_REPO_BY_JOB_Result>("SP_SELECT_LEGAL_REPO_BY_JOB", jOB_IDParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_LEGAL_TRACKING_BY_CASE_Result> SP_SELECT_LEGAL_TRACKING_BY_CASE(string jOB_ID)
        {
            var jOB_IDParameter = jOB_ID != null ?
                new ObjectParameter("JOB_ID", jOB_ID) :
                new ObjectParameter("JOB_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_LEGAL_TRACKING_BY_CASE_Result>("SP_SELECT_LEGAL_TRACKING_BY_CASE", jOB_IDParameter);
        }
    
        public virtual int SP_UPDATE_R3(string jOBID)
        {
            var jOBIDParameter = jOBID != null ?
                new ObjectParameter("JOBID", jOBID) :
                new ObjectParameter("JOBID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_R3", jOBIDParameter);
        }
    }
}
