//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_PMT_RECEIPT
    {
        public string CONTRACT_NO { get; set; }
        public int NO_IN_CONTRACT { get; set; }
        public int INVOICE_RECEIPT_INT_ID { get; set; }
        public Nullable<int> CASH_RECEIPT_ID { get; set; }
        public Nullable<decimal> AMOUNT_EXCL_VAT { get; set; }
        public Nullable<decimal> APPLICABLE_WHT_RATE { get; set; }
        public string CLASSIFICATION_CD { get; set; }
        public Nullable<int> INSTALLMENT_NO { get; set; }
        public Nullable<System.DateTime> INVOICE_RECEIPT_DATE { get; set; }
        public string INVOICE_RECEIPT_NO { get; set; }
        public string PAIRED_INVOICE_NUMBER { get; set; }
        public string PAYMENT_CLASSIFICATION_CD { get; set; }
        public Nullable<System.DateTime> PROCESSING_DATE { get; set; }
        public string STATUS_CD { get; set; }
        public Nullable<decimal> VAT_AMOUNT { get; set; }
        public string RECORD_STATUS { get; set; }
        public Nullable<decimal> PENALTY_CHARGE_AMNT { get; set; }
        public Nullable<System.DateTime> DATA_IMPORT_DATE { get; set; }
    }
}
