//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_DELINQUENCY
    {
        public string CONTRACT_NO { get; set; }
        public Nullable<int> DELINQUENCY_CYCLE_ID { get; set; }
        public Nullable<int> PAYMENT_ID { get; set; }
        public string DELINQUENCY_ON_HOLD_STATUS { get; set; }
        public Nullable<int> DELINQUENCY_STAGE_ID { get; set; }
        public Nullable<System.DateTime> OVERDUE_SINCE { get; set; }
        public Nullable<int> OVERDUE_DAYS { get; set; }
        public Nullable<int> DELINQUENCY_DAYS { get; set; }
        public Nullable<System.DateTime> DELINQUENT_SINCE { get; set; }
        public string DELINQUENCY_REASON_CD { get; set; }
        public Nullable<int> NO_OF_DELINQUENT_PAYMENTS { get; set; }
        public Nullable<decimal> TOTAL_DELINQUENT_AMNT { get; set; }
        public string PENALTY_INTEREST_WAIVER_STATUS { get; set; }
        public Nullable<bool> DELINQUENCY_CLEARED_FG { get; set; }
        public string USER_ALLOCATED { get; set; }
        public string RECORD_STATUS { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> TOTAL_OVERDUE_AMOUNT { get; set; }
        public Nullable<int> INTERACTION_ID { get; set; }
        public Nullable<int> DELINQUENCY_SEQUENCE_ID { get; set; }
        public Nullable<decimal> ARREAR_AMOUNT { get; set; }
        public string STAGE_OFFICER_CHANGED_CD { get; set; }
        public string TRANSMIT_ON_HOLD_CD { get; set; }
        public Nullable<bool> REMINDER_LETTER1_GENERATED_FLG { get; set; }
        public Nullable<bool> REMINDER_LETTER2_GENERATED_FLG { get; set; }
        public Nullable<bool> REMINDER_LETTER3_GENERATED_FLG { get; set; }
        public Nullable<bool> REMINDER_LETTER4_GENERATED_FLG { get; set; }
        public Nullable<bool> REMINDER_LETTER5_GENERATED_FLG { get; set; }
        public Nullable<System.DateTime> OPRATOR_ASSGN_DATE { get; set; }
        public Nullable<System.DateTime> DATA_IMPORT_DATE { get; set; }
    }
}
