//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_CHEQUE
    {
        public string CONTRACT_NO { get; set; }
        public int SR_NO { get; set; }
        public Nullable<int> CHEQUE_SEQUENCE { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string BANK_ID { get; set; }
        public string BRANCH_ID { get; set; }
        public string CHEQUE_CLEARING_CD { get; set; }
        public Nullable<System.DateTime> CHEQUE_DEPOSIT_DATE { get; set; }
        public string CHEQUE_NO { get; set; }
        public Nullable<System.DateTime> CHEQUE_UPLOAD_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<decimal> EMI_AMNT { get; set; }
        public string RECORD_STATUS { get; set; }
        public string REJECTION_STATUS { get; set; }
        public Nullable<System.DateTime> STATUS_DATE { get; set; }
        public Nullable<bool> PDC_LETTER_GENERATED_FLG { get; set; }
        public Nullable<System.DateTime> DATA_IMPORT_DATE { get; set; }
        public string COMP_CODE { get; set; }
        public string COMP_BRANCH_CODE { get; set; }
    }
}
