//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_COST
    {
        public string CONTRACT_NO { get; set; }
        public int COST_SEQ_NO { get; set; }
        public Nullable<decimal> COST_AMNT { get; set; }
        public string COST_CLASSIFICATION_CD { get; set; }
        public string COST_STATUS_CD { get; set; }
        public string COST_TYPE_CD { get; set; }
        public Nullable<System.DateTime> COST_UPLOADED_DATE { get; set; }
        public Nullable<System.DateTime> DATE_CHARGED { get; set; }
        public Nullable<System.DateTime> DD_DATE { get; set; }
        public string DELETED_BY { get; set; }
        public Nullable<decimal> OUTSTANDING_COST_AMNT { get; set; }
        public Nullable<decimal> OUTSTANDING_VAT { get; set; }
        public Nullable<int> PAYMENT_ID { get; set; }
        public Nullable<System.DateTime> RECOVERY_DATE { get; set; }
        public string REMARKS { get; set; }
        public string RETURN_REMARKS { get; set; }
        public string THIRD_PARTY_NAME { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public Nullable<decimal> VAT_PAID { get; set; }
        public string RECORD_STATUS { get; set; }
        public Nullable<System.DateTime> DATA_IMPORT_DATE { get; set; }
    }
}
