//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CONTRACT_CUST
    {
        public string CONTRACT_NO { get; set; }
        public string CUST_CODE { get; set; }
        public string CUST_BR_TYPE { get; set; }
        public Nullable<int> GUARANTOR_SEQ { get; set; }
        public string SEND_SMS { get; set; }
        public Nullable<System.DateTime> DATA_IMPORT_DATE { get; set; }
    }
}
