//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_RPS
    {
        public string RPS_CONTRACT_NO { get; set; }
        public Nullable<System.DateTime> RPS_R3_DATE { get; set; }
        public Nullable<System.DateTime> RPS_REMENPTION_DATE { get; set; }
        public string RPS_OA { get; set; }
        public string RPS_REMARKETING_STATUS { get; set; }
        public Nullable<System.DateTime> RPS_AUCTION_DATE { get; set; }
        public Nullable<decimal> RPS_AUCTION_PRICE_AMT { get; set; }
        public Nullable<decimal> RPS_AUCTION_PRICE_VAT { get; set; }
        public string RPS_AUCTION_HOUSE { get; set; }
    }
}
