//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ACT_LOG
    {
        public long AL_ID { get; set; }
        public string AL_USER_LOGIN { get; set; }
        public string AL_PROG_CODE { get; set; }
        public string AL_DESC { get; set; }
        public Nullable<System.DateTime> AC_DATE { get; set; }
    }
}
