//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BATCH_LOG
    {
        public long BATCH_LOG_ID { get; set; }
        public string BATCH_CODE { get; set; }
        public string BATCH_STEP { get; set; }
        public string BATCH_DESC { get; set; }
        public string BATCH_RESULT_FLAG { get; set; }
        public Nullable<System.DateTime> BATCH_DATE { get; set; }
    }
}
