//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BANKRUPTCY_FRAUD_D
    {
        public int BFD_ID { get; set; }
        public string BFD_HID { get; set; }
        public string BFD_CONTRACT_NO { get; set; }
        public string BFD_CARD_NO { get; set; }
        public string BFD_FIRSTNAME { get; set; }
        public string BFD_LASTNAME { get; set; }
        public string BFD_COURTNAME { get; set; }
        public string BFD_REDCODE { get; set; }
        public string BFD_PLAINTIFF_NAME { get; set; }
        public string BFD_DEFENDANT_NAME { get; set; }
        public Nullable<System.DateTime> BFD_RECEIVING_ORDER_DATE { get; set; }
        public Nullable<System.DateTime> BFD_SUBMIT_DUE_DATE { get; set; }
        public Nullable<System.DateTime> BFD_CANCEL_RECEIVING_ORDER_DATE { get; set; }
        public Nullable<System.DateTime> BFD_COMPROMISE_BEFORE_DATE { get; set; }
        public Nullable<System.DateTime> BFD_CANCEL_COMPROMISE_BAFORE_DATE { get; set; }
        public Nullable<System.DateTime> BFD_ORDER_BANKRUPCTY_DATE { get; set; }
        public Nullable<System.DateTime> BFD_COMPROMISE_AFTER_DATE { get; set; }
        public Nullable<System.DateTime> BFD_CANCEL_COMPROMISE_AFTER_DATE { get; set; }
        public Nullable<System.DateTime> BFD_SUBMIT_AFTER_DUE_DATE { get; set; }
        public Nullable<System.DateTime> BFD_CANCEL_BANKRUPTCY_DATE { get; set; }
        public Nullable<System.DateTime> BFD_DISCHANGED_BANKRUPTCY_DATE { get; set; }
        public Nullable<System.DateTime> BFD_DISMISSAL_DATE { get; set; }
        public Nullable<System.DateTime> BFD_DISPOSE_CASE_DATE { get; set; }
        public Nullable<System.DateTime> BFD_FILING_DATE { get; set; }
        public string BFD_REMARK { get; set; }
        public string BFD_CREATE_BY { get; set; }
        public Nullable<System.DateTime> BFD_CREATE_DATE { get; set; }
        public string BFD_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> BFD_UPDATE_DATE { get; set; }
        public string BFD_STATUS { get; set; }
    }
}
