//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DOCUMENT
    {
        public string TDOC_JOB_ID { get; set; }
        public string TDOC_CONTRACT_NO { get; set; }
        public string TDOC_DOC_CODE { get; set; }
        public string TDOC_SUCC_FLAG { get; set; }
        public string TDOC_FAIL_FLAG { get; set; }
        public string TDOC_REASON_CODE { get; set; }
        public string TDOC_REMARK { get; set; }
        public string TDOC_CREATE_BY { get; set; }
        public Nullable<System.DateTime> TDOC_CRREATE_DATE { get; set; }
        public string TDOC_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> TDOC_UPDATE_DATE { get; set; }
        public string TDOC_STATUS { get; set; }
    }
}
