//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JUDGMENTDEBTOR_ATTACHMENT
    {
        public string JDA_HID { get; set; }
        public string JDA_JOB_ID { get; set; }
        public int JDA_SEQUENCE { get; set; }
        public string JDA_FILE_NAME { get; set; }
        public string JDA_FILE_PATH { get; set; }
        public string JDA_DESCRIPTION { get; set; }
        public string JDA_CREATE_BY { get; set; }
        public Nullable<System.DateTime> JDA_CREATE_DATE { get; set; }
    }
}
