//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JUDGMENTDEBTOR_PAYMENT
    {
        public string JDP_HID { get; set; }
        public int JDP_TERM { get; set; }
        public string JDP_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> JDP_DUEDATE { get; set; }
        public Nullable<decimal> JDP_INSTALLMENT { get; set; }
        public string JDP_CREATE_BY { get; set; }
        public Nullable<System.DateTime> JDP_CREATE_DATE { get; set; }
        public string JDP_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> JDP_UPDATE_DATE { get; set; }
        public string JDP_STATUS { get; set; }
    }
}
