//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LOGIN_HISTORY
    {
        public long CL_ID { get; set; }
        public string CL_USER_LOGIN { get; set; }
        public string CL_ROLE_CODE { get; set; }
        public string CL_IP_ADDRESS { get; set; }
        public Nullable<System.DateTime> CL_LOGIN_DATE { get; set; }
        public Nullable<System.DateTime> CL_LAST_ACT_DATE { get; set; }
        public string CL_STATUS { get; set; }
    }
}
