//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCLS.WEB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REPO_NOTE
    {
        public long NOTE_ID { get; set; }
        public string NOTE_JOB_ID { get; set; }
        public string NOTE_CONTRACT_NO { get; set; }
        public string NOTE_REMARK { get; set; }
        public string NOTE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> NOTE_CREATE_DATE { get; set; }
        public string NOTE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> NOTE_UPDATE_DATE { get; set; }
        public string NOTE_STATUS { get; set; }
    }
}
